export type Question = {
  id: string;
  segmentId: string;
  reference: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

function shuffleArray<T>(array: T[]): T[] {
  return [...array].sort(() => Math.random() - 0.5);
}

const mockQuestions: Question[] = [
  {
    id: '1',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the first day?',
    options: ['Light', 'Earth', 'Heaven', 'Water'],
    correctIndex: 0,
    explanation: 'On the first day, God created light and separated it from darkness.',
    difficulty: 'easy',
  },
  {
    id: '2',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the second day?',
    options: ['Firmament', 'Sun and Moon', 'Sea creatures', 'Land'],
    correctIndex: 0,
    explanation: 'On the second day, God created the firmament to separate waters above and below.',
    difficulty: 'easy',
  },
  {
    id: '3',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the third day?',
    options: ['Dry land and vegetation', 'Fish and birds', 'Animals', 'Humans'],
    correctIndex: 0,
    explanation: 'On the third day, God gathered the waters to reveal dry land and caused vegetation to grow.',
    difficulty: 'easy',
  },
  {
    id: '4',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fourth day?',
    options: ['Sun, Moon, and stars', 'Trees and plants', 'Birds', 'Sea creatures'],
    correctIndex: 0,
    explanation: 'On the fourth day, God created the sun, moon, and stars to govern day and night.',
    difficulty: 'medium',
  },
  {
    id: '5',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fifth day?',
    options: ['Sea creatures and birds', 'Humans', 'Land animals', 'Vegetation'],
    correctIndex: 0,
    explanation: 'On the fifth day, God created sea creatures and birds to fill the waters and sky.',
    difficulty: 'medium',
  },
  {
    id: '6',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the sixth day?',
    options: ['Land animals and humans', 'Fish', 'Plants', 'Stars'],
    correctIndex: 0,
    explanation: 'On the sixth day, God created land animals and humans in His image.',
    difficulty: 'easy',
  },
  {
    id: '7',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do on the seventh day?',
    options: ['Rested', 'Created more light', 'Made the sea', 'Planted trees'],
    correctIndex: 0,
    explanation: 'On the seventh day, God rested from His work of creation.',
    difficulty: 'easy',
  },
  {
    id: '8',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the first thing God called "good"?',
    options: ['Light', 'Firmament', 'Dry land', 'Sun'],
    correctIndex: 0,
    explanation: 'After creating light on the first day, God saw that it was good.',
    difficulty: 'medium',
  },
  {
    id: '9',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create the dry land?',
    options: ['Gathered the waters', 'Spoke it into existence', 'Formed it from clay', 'Brought it from another place'],
    correctIndex: 0,
    explanation: 'God gathered the waters together to allow the dry land to appear.',
    difficulty: 'medium',
  },
  {
    id: '10',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created to fill the waters and the sky?',
    options: ['Sea creatures and birds', 'Land animals', 'Humans', 'Plants'],
    correctIndex: 0,
    explanation: 'On the fifth day, God blessed the sea creatures and birds to be fruitful and multiply.',
    difficulty: 'easy',
  },
  {
    id: '11',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which of creation was made before the sun and moon?',
    options: ['Light', 'Plants', 'Fish', 'Humans'],
    correctIndex: 0,
    explanation: 'Light was created on the first day before the sun and moon on the fourth day.',
    difficulty: 'medium',
  },
  {
    id: '12',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What role did God give to fish and birds?',
    options: ['Be fruitful and multiply', 'Rule the earth', 'Guard Eden', 'Worship'],
    correctIndex: 0,
    explanation: 'God blessed the fish and birds to be fruitful and multiply and fill the waters and sky.',
    difficulty: 'hard',
  },
  {
    id: '13',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which two humans are introduced in Genesis 2 and 3?',
    options: ['Adam and Eve', 'Noah and Sarah', 'Abraham and Lot', 'Isaac and Rebekah'],
    correctIndex: 0,
    explanation: 'Adam and Eve are the first humans in Genesis 2 and 3.',
    difficulty: 'easy',
  },
  {
    id: '14',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Where did God place Adam and Eve after creation?',
    options: ['Garden of Eden', 'Mount Sinai', 'Jerusalem', 'Nile River'],
    correctIndex: 0,
    explanation: 'God placed them in the Garden of Eden in Genesis chapter 2.',
    difficulty: 'easy',
  },
  {
    id: '15',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What instruction was given to Adam about the tree of knowledge?',
    options: ['Do not eat its fruit', 'Share fruit with others', 'Water it daily', 'Build a fence around it'],
    correctIndex: 0,
    explanation: 'God commanded Adam not to eat from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '16',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Who tempted Eve to eat the forbidden fruit?',
    options: ['The serpent', 'An angel', 'Adam', 'A neighbor'],
    correctIndex: 0,
    explanation: 'A serpent tempted Eve to eat the fruit from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '17',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the consequence for Adam after the fall?',
    options: ['Toil and work the ground', 'Flying', 'Immortality', 'Speak new languages'],
    correctIndex: 0,
    explanation: 'After the fall, Adam was told he would toil and work the ground for food.',
    difficulty: 'hard',
  },
  {
    id: '18',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What consequences did Eve receive after disobedience?',
    options: ['Increased pain in childbirth', 'Longer life', 'Ruler over Adam', 'Freedom from work'],
    correctIndex: 0,
    explanation: 'God told Eve childbirth would be painful and childbearing would involve sorrow.',
    difficulty: 'hard',
  },
  {
    id: '19',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God place at the east of Eden after the fall?',
    options: ['Cherubim and flame', 'An angelic choir', 'A golden crown', 'A waterfall'],
    correctIndex: 0,
    explanation: 'God placed cherubim and a flaming sword to guard the way to the tree of life.',
    difficulty: 'hard',
  },
  {
    id: '20',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the first human relationship described in Genesis 2?',
    options: ['Man and wife', 'Father and son', 'Teacher and student', 'King and servant'],
    correctIndex: 0,
    explanation: 'Genesis 2 describes the creation of woman as a companion for man.',
    difficulty: 'medium',
  },
  {
    id: '21',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God use to create Eve?',
    options: ['A rib from Adam', 'Dust from the ground', 'Water from the river', 'A branch from the tree'],
    correctIndex: 0,
    explanation: 'God took a rib from Adam and formed Eve as his companion.',
    difficulty: 'medium',
  },
  {
    id: '22',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the name of the garden where Adam and Eve lived?',
    options: ['Garden of Eden', 'Garden of Gethsemane', 'Garden of Olives', 'Garden of Paradise'],
    correctIndex: 0,
    explanation: 'God planted the Garden of Eden in the east and placed Adam and Eve there.',
    difficulty: 'easy',
  },
  {
    id: '23',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent promise Eve if she ate the fruit?',
    options: ['Eyes would be opened, become like God', 'Eternal life', 'Power over animals', 'Wisdom without consequences'],
    correctIndex: 0,
    explanation: 'The serpent deceived Eve by saying eating the fruit would make her like God, knowing good and evil.',
    difficulty: 'hard',
  },
  {
    id: '24',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve do after eating the forbidden fruit?',
    options: ['Hid from God', 'Celebrated', 'Told the serpent', 'Ate more fruit'],
    correctIndex: 0,
    explanation: 'When they heard God walking, Adam and Eve hid among the trees of the garden.',
    difficulty: 'medium',
  },
  {
    id: '25',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve after the fall?',
    options: ['Garments of skin', 'Crowns of gold', 'Shoes of leather', 'Houses of wood'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and Eve to clothe their nakedness.',
    difficulty: 'hard',
  },
  {
    id: '26',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How many days did God take to create the world?',
    options: ['6 days', '7 days', '5 days', '8 days'],
    correctIndex: 0,
    explanation: 'God created the heavens and the earth in six days and rested on the seventh.',
    difficulty: 'medium',
  },
  {
    id: '27',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the tree called that Adam and Eve were forbidden to eat from?',
    options: ['Tree of the knowledge of good and evil', 'Tree of life', 'Tree of wisdom', 'Tree of fruit'],
    correctIndex: 0,
    explanation: 'God commanded them not to eat from the tree of the knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '28',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the serpent would eat after the fall?',
    options: ['Dust', 'Fruit', 'Grass', 'Other serpents'],
    correctIndex: 0,
    explanation: 'God cursed the serpent to crawl on its belly and eat dust all the days of its life.',
    difficulty: 'hard',
  },
  {
    id: '29',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the order of creation on the first three days?',
    options: ['Light, firmament, dry land and plants', 'Plants, light, firmament', 'Dry land, light, firmament', 'Firmament, light, plants'],
    correctIndex: 0,
    explanation: 'Day 1: light; Day 2: firmament; Day 3: dry land and vegetation.',
    difficulty: 'hard',
  },
  {
    id: '30',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created on the fourth, fifth, and sixth days?',
    options: ['Lights, sea creatures and birds, land animals and humans', 'Humans, birds, lights', 'Birds, lights, sea creatures', 'Land animals, humans, lights'],
    correctIndex: 0,
    explanation: 'Day 4: sun/moon/stars; Day 5: sea creatures/birds; Day 6: land animals/humans.',
    difficulty: 'hard',
  },
  {
    id: '31',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God rest on the seventh day?',
    options: ['He finished His work of creation', 'He was tired', 'To set an example', 'To contemplate'],
    correctIndex: 0,
    explanation: 'God had completed the work He had been doing, so He rested on the seventh day.',
    difficulty: 'medium',
  },
  {
    id: '32',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say about all His creation?',
    options: ['It was very good', 'It was good', 'It was excellent', 'It was perfect'],
    correctIndex: 0,
    explanation: 'After creating humans, God saw everything that He had made, and it was very good.',
    difficulty: 'medium',
  },
  {
    id: '33',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s first task in the garden?',
    options: ['To work and keep the garden', 'To name the animals', 'To build a house', 'To plant trees'],
    correctIndex: 0,
    explanation: 'God put Adam in the garden to work it and keep it.',
    difficulty: 'hard',
  },
  {
    id: '34',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Eve say the serpent told her about the fruit?',
    options: ['We will not surely die', 'It will make us sick', 'It will give us power', 'It will make us happy'],
    correctIndex: 0,
    explanation: 'Eve told God that the serpent said they would not surely die if they ate the fruit.',
    difficulty: 'hard',
  },
  {
    id: '35',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do to the ground because of Adam\'s sin?',
    options: ['Cursed it with thorns and thistles', 'Made it fertile', 'Flooded it', 'Burned it'],
    correctIndex: 0,
    explanation: 'Because of Adam, the ground was cursed and would produce thorns and thistles.',
    difficulty: 'hard',
  },
  // New medium questions
  {
    id: '36',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the purpose of the firmament created on the second day?',
    options: ['To separate waters above and below', 'To hold the stars', 'To provide light', 'To support land'],
    correctIndex: 0,
    explanation: 'The firmament divided the waters that were under it from the waters above it.',
    difficulty: 'medium',
  },
  {
    id: '37',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was vegetation created before the sun?',
    options: ['God provided light directly until the fourth day', 'The sun was not needed for plants', 'Plants grew at night', 'The moon provided light'],
    correctIndex: 0,
    explanation: 'God created light on day one, and vegetation on day three, before creating the sun on day four.',
    difficulty: 'medium',
  },
  {
    id: '38',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What blessing did God give to sea creatures and birds?',
    options: ['Be fruitful and multiply', 'Rule over the earth', 'Live forever', 'Speak languages'],
    correctIndex: 0,
    explanation: 'God blessed them to be fruitful, multiply, and fill the seas and skies.',
    difficulty: 'medium',
  },
  {
    id: '39',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create man according to Genesis 1?',
    options: ['In His image and likeness', 'From clay', 'From a tree', 'From water'],
    correctIndex: 0,
    explanation: 'God said, "Let us make mankind in our image, in our likeness."',
    difficulty: 'medium',
  },
  {
    id: '40',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God give humans dominion over?',
    options: ['Fish, birds, livestock, and earth', 'Angels', 'God Himself', 'Each other'],
    correctIndex: 0,
    explanation: 'God gave humans rule over the fish, birds, livestock, and all the earth.',
    difficulty: 'medium',
  },
  {
    id: '41',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s role in naming the animals?',
    options: ['To see if there was a suitable helper', 'To count them', 'To feed them', 'To hunt them'],
    correctIndex: 0,
    explanation: 'God brought animals to Adam to name them and find a companion.',
    difficulty: 'medium',
  },
  {
    id: '42',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God create Eve?',
    options: ['As a helper suitable for man', 'To work the garden', 'To name animals', 'To guard the trees'],
    correctIndex: 0,
    explanation: 'God said it was not good for man to be alone, so He made a helper.',
    difficulty: 'medium',
  },
  {
    id: '43',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What trees were in the midst of the garden?',
    options: ['Tree of life and tree of knowledge', 'Tree of wisdom and tree of fruit', 'Tree of good and tree of evil', 'Tree of peace and tree of war'],
    correctIndex: 0,
    explanation: 'The tree of life and the tree of the knowledge of good and evil were in the garden.',
    difficulty: 'medium',
  },
  {
    id: '44',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent question Eve about?',
    options: ['God\'s command regarding the tree', 'The garden\'s location', 'Adam\'s name', 'The weather'],
    correctIndex: 0,
    explanation: 'The serpent asked Eve about what God had said concerning eating from the tree.',
    difficulty: 'medium',
  },
  {
    id: '45',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did Eve respond to the serpent\'s temptation?',
    options: ['She ate the fruit and gave some to Adam', 'She refused', 'She told God', 'She ran away'],
    correctIndex: 0,
    explanation: 'Eve took the fruit, ate it, and gave some to Adam who was with her.',
    difficulty: 'medium',
  },
  {
    id: '46',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve realize after eating the fruit?',
    options: ['They were naked', 'They were hungry', 'They were tired', 'They were happy'],
    correctIndex: 0,
    explanation: 'Their eyes were opened, and they knew they were naked.',
    difficulty: 'medium',
  },
  {
    id: '47',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God ask Adam when He confronted him?',
    options: ['Where are you?', 'What have you done?', 'Why did you eat?', 'Who told you?'],
    correctIndex: 0,
    explanation: 'God called to Adam and asked, "Where are you?"',
    difficulty: 'medium',
  },
  {
    id: '48',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s response to God\'s question?',
    options: ['I heard you and hid because I was naked', 'I ate the fruit', 'The serpent made me', 'I don\'t know'],
    correctIndex: 0,
    explanation: 'Adam admitted he hid because he was afraid due to his nakedness.',
    difficulty: 'medium',
  },
  {
    id: '49',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What curse did God place on the serpent?',
    options: ['Crawl on belly and eat dust', 'Lose its voice', 'Die immediately', 'Become invisible'],
    correctIndex: 0,
    explanation: 'The serpent was cursed to crawl on its belly and eat dust.',
    difficulty: 'medium',
  },
  {
    id: '50',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What enmity did God put between the serpent and the woman?',
    options: ['Between offspring', 'Between bodies', 'Between minds', 'Between homes'],
    correctIndex: 0,
    explanation: 'God put enmity between the serpent\'s offspring and the woman\'s offspring.',
    difficulty: 'medium',
  },
  {
    id: '51',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the woman\'s desire would be?',
    options: ['For her husband', 'For the garden', 'For the fruit', 'For the serpent'],
    correctIndex: 0,
    explanation: 'God said the woman\'s desire would be for her husband, and he would rule over her.',
    difficulty: 'medium',
  },
  {
    id: '52',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What name did Adam give to Eve?',
    options: ['Woman, because she was taken from man', 'Eve, because she was the mother of all living', 'Helper, because she helped him', 'Companion, because she was his friend'],
    correctIndex: 0,
    explanation: 'Adam called his wife\'s name Woman, for she was taken out of Man.',
    difficulty: 'medium',
  },
  {
    id: '53',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve to wear?',
    options: ['Garments of skin', 'Leaves', 'Animal fur', 'Cloth'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and his wife and clothed them.',
    difficulty: 'medium',
  },
  {
    id: '54',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God drive Adam and Eve out of the garden?',
    options: ['To prevent them from eating from the tree of life', 'Because they were disobedient', 'To punish them', 'To start a new life'],
    correctIndex: 0,
    explanation: 'God drove them out lest they eat from the tree of life and live forever.',
    difficulty: 'medium',
  },
  {
    id: '55',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What guarded the way to the tree of life?',
    options: ['Cherubim and a flaming sword', 'Angels and a wall', 'Animals and thorns', 'God Himself'],
    correctIndex: 0,
    explanation: 'Cherubim and a flaming sword flashing back and forth guarded the way.',
    difficulty: 'medium',
  },
  // New hard questions
  {
    id: '56',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the significance of God creating in six days and resting on the seventh?',
    options: ['Establishes the pattern for human work and rest', 'Shows God\'s power', 'Demonstrates order', 'Teaches counting'],
    correctIndex: 0,
    explanation: 'The six-day creation and seventh-day rest set the foundation for the Sabbath and human rhythms.',
    difficulty: 'hard',
  },
  {
    id: '57',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why might God have created light before the sun?',
    options: ['To show His sovereignty over natural sources', 'The sun was not yet formed', 'Light existed independently', 'To confuse scientists'],
    correctIndex: 0,
    explanation: 'God\'s creation of light apart from the sun demonstrates His supreme authority over all sources of light.',
    difficulty: 'hard',
  },
  {
    id: '58',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the creation of humans "in God\'s image" imply?',
    options: ['Capacity for relationship and moral choice', 'Physical appearance', 'Immortality', 'Power over nature'],
    correctIndex: 0,
    explanation: 'Being made in God\'s image gives humans the unique ability to relate to God and make moral decisions.',
    difficulty: 'hard',
  },
  {
    id: '59',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was Adam\'s naming of animals significant?',
    options: ['Demonstrated his authority and revealed no equal companion', 'To learn their names', 'For scientific classification', 'To communicate with them'],
    correctIndex: 0,
    explanation: 'By naming animals, Adam exercised dominion and realized he needed a suitable partner.',
    difficulty: 'hard',
  },
  {
    id: '60',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the tree of life represent in the garden?',
    options: ['Eternal life and sustenance', 'Knowledge', 'Wisdom', 'Power'],
    correctIndex: 0,
    explanation: 'The tree of life offered immortality, which is why access was barred after the fall.',
    difficulty: 'hard',
  },
  {
    id: '61',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the serpent\'s temptation reveal deception?',
    options: ['Twists God\'s words and promises false benefits', 'Uses force', 'Ignores the command', 'Denies God\'s existence'],
    correctIndex: 0,
    explanation: 'The serpent misquotes God and promises godlike status, leading to disobedience.',
    difficulty: 'hard',
  },
  {
    id: '62',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does Adam and Eve hiding from God symbolize?',
    options: ['Recognition of guilt and broken relationship', 'Fear of punishment', 'Physical hiding', 'Avoiding conversation'],
    correctIndex: 0,
    explanation: 'Hiding symbolizes the shame and separation from God caused by sin.',
    difficulty: 'hard',
  },
  {
    id: '63',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God curse the ground for Adam\'s sake?',
    options: ['To reflect the broken relationship between man and creation', 'To make work harder', 'To punish the earth', 'To grow thorns'],
    correctIndex: 0,
    explanation: 'The curse on the ground mirrors how sin disrupted harmony in creation.',
    difficulty: 'hard',
  },
  {
    id: '64',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the enmity between serpent\'s and woman\'s offspring foreshadow?',
    options: ['The ongoing battle between good and evil', 'Family conflicts', 'Animal attacks', 'Garden disputes'],
    correctIndex: 0,
    explanation: 'This points to the cosmic conflict between Satan\'s forces and humanity, culminating in Christ\'s victory.',
    difficulty: 'hard',
  },
  {
    id: '65',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does Eve\'s increased pain in childbirth relate to the fall?',
    options: ['Symbolizes the pain and sorrow sin brings to relationships', 'Physical only', 'Punishment for eating', 'Medical condition'],
    correctIndex: 0,
    explanation: 'The pain represents how sin complicates and brings suffering to human experiences.',
    difficulty: 'hard',
  },
  {
    id: '66',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the significance of God making garments of skin?',
    options: ['First sacrifice and covering of sin', 'Fashion statement', 'Protection from cold', 'Cultural tradition'],
    correctIndex: 0,
    explanation: 'The animal skins imply death and sacrifice, foreshadowing Christ\'s atonement.',
    difficulty: 'hard',
  },
  {
    id: '67',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was the tree of life guarded after the fall?',
    options: ['To prevent eternal life in a fallen state', 'To protect it', 'To punish humans', 'To keep animals out'],
    correctIndex: 0,
    explanation: 'Immortality in sin would be a curse, so access to eternal life was blocked.',
    difficulty: 'hard',
  },
  {
    id: '68',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does Adam\'s naming of Eve as "Woman" signify?',
    options: ['Her origin from man and unity with him', 'Her beauty', 'Her role', 'Her name'],
    correctIndex: 0,
    explanation: 'Calling her "Woman" emphasizes she was taken from man, highlighting their oneness.',
    difficulty: 'hard',
  },
  {
    id: '69',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the creation account contrast with ancient Near Eastern myths?',
    options: ['God is sovereign and good, not in conflict with chaos', 'More violent', 'Less detailed', 'Similar stories'],
    correctIndex: 0,
    explanation: 'Unlike myths where gods battle chaos, God creates effortlessly and declares it good.',
    difficulty: 'hard',
  },
  {
    id: '70',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What theological truth does the Sabbath rest teach?',
    options: ['God\'s work is complete and sufficient', 'God needs rest', 'Creation was tiring', 'Time management'],
    correctIndex: 0,
    explanation: 'God\'s rest on the seventh day shows His creation is finished and perfect.',
    difficulty: 'hard',
  },
  {
    id: '71',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God curse the serpent to eat dust?',
    options: ['Represents defeat and humiliation', 'Dietary change', 'Punishment', 'New food source'],
    correctIndex: 0,
    explanation: 'Eating dust symbolizes the serpent\'s (Satan\'s) ultimate defeat and low status.',
    difficulty: 'hard',
  },
  {
    id: '72',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does God\'s question "Where are you?" reveal about Him?',
    options: ['His desire for relationship despite sin', 'Anger', 'Confusion', 'Power'],
    correctIndex: 0,
    explanation: 'God seeks out the hiding humans, showing His loving pursuit even after disobedience.',
    difficulty: 'hard',
  },
  {
    id: '73',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the fall affect human dominion over creation?',
    options: ['Makes it toilsome instead of harmonious', 'Increases power', 'Removes responsibility', 'Adds ease'],
    correctIndex: 0,
    explanation: 'Work becomes difficult, reflecting how sin disrupted the original harmony.',
    difficulty: 'hard',
  },
  {
    id: '74',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What hope is implied in the curse on the serpent?',
    options: ['Ultimate victory through the woman\'s offspring', 'No hope', 'Serpent\'s victory', 'Peace'],
    correctIndex: 0,
    explanation: 'The promise of enmity and the serpent\'s defeat points to Christ\'s triumph over evil.',
    difficulty: 'hard',
  },
  {
    id: '75',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God create Eve from Adam\'s rib rather than dust?',
    options: ['To show equality and unity in marriage', 'Easier method', 'Different material', 'Adam\'s preference'],
    correctIndex: 0,
    explanation: 'Taking from Adam\'s side signifies partnership and oneness in the marital relationship.',
    difficulty: 'hard',
  },
  {
    id: '76',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who were the two sons of Adam and Eve in Genesis 4?',
    options: ['Cain and Abel', 'Shem and Ham', 'Isaac and Ishmael', 'Esau and Jacob'],
    correctIndex: 0,
    explanation: 'Genesis 4 introduces Cain and Abel as sons of Adam and Eve.',
    difficulty: 'easy',
  },
  {
    id: '77',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What was Abel\'s occupation?',
    options: ['Farmer', 'Shepherd', 'Carpenter', 'Hunter'],
    correctIndex: 1,
    explanation: 'Abel kept flocks, while Cain worked the ground.',
    difficulty: 'easy',
  },
  {
    id: '78',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What was Cain\'s occupation?',
    options: ['Worker of the ground', 'Priest', 'King', 'Fisherman'],
    correctIndex: 0,
    explanation: 'Cain is described as one who worked the soil.',
    difficulty: 'easy',
  },
  {
    id: '79',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who was killed by his brother in Genesis 4?',
    options: ['Cain', 'Abel', 'Seth', 'Enoch'],
    correctIndex: 1,
    explanation: 'Cain rose up against Abel and killed him in the field.',
    difficulty: 'easy',
  },
  {
    id: '80',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who was born to Adam and Eve after Abel\'s death?',
    options: ['Noah', 'Enosh', 'Seth', 'Lamech'],
    correctIndex: 2,
    explanation: 'Eve said God appointed Seth in place of Abel.',
    difficulty: 'easy',
  },
  {
    id: '81',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Why did God regard Abel\'s offering?',
    options: ['It was from the firstborn of his flock and fat portions', 'It was larger', 'It came first in time', 'It was grain with oil'],
    correctIndex: 0,
    explanation: 'Genesis 4 highlights that Abel brought firstborn portions from his flock.',
    difficulty: 'medium',
  },
  {
    id: '82',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What warning did God give Cain before he sinned?',
    options: ['Leave the land', 'Sin is crouching at the door; you must rule over it', 'Offer another animal', 'Build an altar'],
    correctIndex: 1,
    explanation: 'God warned Cain that sin desired him, but he should master it.',
    difficulty: 'medium',
  },
  {
    id: '83',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How did Cain answer God when asked about Abel?',
    options: ['I buried him', 'I do not know; am I my brother\'s keeper?', 'He left the land', 'He is with Seth'],
    correctIndex: 1,
    explanation: 'Cain responded with denial and the phrase about being his brother\'s keeper.',
    difficulty: 'medium',
  },
  {
    id: '84',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What curse did Cain receive?',
    options: ['He would no longer farm', 'He would be a fugitive and wanderer', 'He would lose speech', 'He would be childless'],
    correctIndex: 1,
    explanation: 'God declared Cain would be a restless wanderer on the earth.',
    difficulty: 'medium',
  },
  {
    id: '85',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What did God place on Cain?',
    options: ['A crown', 'A mark to protect him from being killed', 'A chain', 'A scarlet robe'],
    correctIndex: 1,
    explanation: 'The mark on Cain served as protection from vengeance.',
    difficulty: 'medium',
  },
  {
    id: '86',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Where did Cain settle after leaving the LORD\'s presence?',
    options: ['Canaan', 'Shinar', 'Nod, east of Eden', 'Egypt'],
    correctIndex: 2,
    explanation: 'Genesis says Cain settled in the land of Nod, east of Eden.',
    difficulty: 'medium',
  },
  {
    id: '87',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What city did Cain build and name after his son?',
    options: ['Enoch', 'Babel', 'Ur', 'Jericho'],
    correctIndex: 0,
    explanation: 'Cain named the city after his son Enoch.',
    difficulty: 'medium',
  },
  {
    id: '88',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Which descendant of Cain is known for saying he killed a man?',
    options: ['Jabal', 'Tubal-cain', 'Lamech', 'Enosh'],
    correctIndex: 2,
    explanation: 'Lamech\'s poem records his violent boast.',
    difficulty: 'medium',
  },
  {
    id: '89',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'In Seth\'s line, what began in the days of Enosh?',
    options: ['People began to call on the name of the LORD', 'People built towers', 'People discovered bronze', 'People crossed the sea'],
    correctIndex: 0,
    explanation: 'Genesis 4:26 notes that people began calling on the LORD\'s name.',
    difficulty: 'medium',
  },
  {
    id: '90',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who is described as walking with God and then not being found?',
    options: ['Methuselah', 'Noah', 'Enoch', 'Seth'],
    correctIndex: 2,
    explanation: 'Genesis 5 says Enoch walked with God, then God took him.',
    difficulty: 'medium',
  },
  {
    id: '91',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What theological point is emphasized by repeated genealogical phrase "and he died" in Genesis 5?',
    options: ['Human kingship', 'The consequence of sin and mortality', 'Agricultural decline', 'Migration patterns'],
    correctIndex: 1,
    explanation: 'The repetition underscores death as the result of the fall.',
    difficulty: 'hard',
  },
  {
    id: '92',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How does Enoch stand out within the genealogy of Genesis 5?',
    options: ['He had no children', 'He lived in Egypt', 'He did not die in the usual way', 'He built the ark'],
    correctIndex: 2,
    explanation: 'Unlike the repeated "and he died," Enoch was taken by God.',
    difficulty: 'hard',
  },
  {
    id: '93',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What is one major contrast between Cain\'s line and Seth\'s line in Genesis 4-5?',
    options: ['Cain\'s line is unnamed', 'Seth\'s line includes those who call on the LORD', 'Cain\'s line has no cities', 'Seth\'s line rejects worship'],
    correctIndex: 1,
    explanation: 'Seth\'s line is linked with worship and covenant hope.',
    difficulty: 'hard',
  },
  {
    id: '94',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What does Noah\'s name signify according to Lamech in Genesis 5?',
    options: ['Victory in war', 'Rest or comfort from cursed ground', 'Great wisdom', 'Long life'],
    correctIndex: 1,
    explanation: 'Lamech connects Noah\'s name with relief from painful toil.',
    difficulty: 'hard',
  },
  {
    id: '95',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How is human corruption described in Genesis 6:5?',
    options: ['Occasional wrongdoing', 'Only kings were corrupt', 'Every inclination of human thoughts was continually evil', 'Mostly righteous with some faults'],
    correctIndex: 2,
    explanation: 'The verse presents a deep and pervasive moral corruption.',
    difficulty: 'hard',
  },
  {
    id: '96',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What does Genesis 6 say God would limit concerning humans?',
    options: ['Their language', 'Their lifespan to 120 years', 'Their food', 'Their travel'],
    correctIndex: 1,
    explanation: 'Genesis 6:3 states human days would be 120 years.',
    difficulty: 'hard',
  },
  {
    id: '97',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What is said about Noah in relation to his generation?',
    options: ['He was mighty in battle', 'He was blameless and walked with God', 'He founded cities', 'He served as a priest king'],
    correctIndex: 1,
    explanation: 'Noah is described as righteous and blameless among his contemporaries.',
    difficulty: 'hard',
  },
  {
    id: '98',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What material was Noah instructed to use for the ark?',
    options: ['Cedar', 'Olive wood', 'Gopher wood', 'Acacia'],
    correctIndex: 2,
    explanation: 'God instructed Noah to build the ark of gopher wood.',
    difficulty: 'hard',
  },
  {
    id: '99',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What does God\'s covenant with Noah in Genesis 6 primarily concern before the flood?',
    options: ['Land inheritance', 'Preservation through judgment', 'Temple worship', 'Kingship'],
    correctIndex: 1,
    explanation: 'God promises Noah survival through the coming judgment.',
    difficulty: 'hard',
  },
  {
    id: '100',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What repeated statement summarizes Noah\'s response to God\'s commands?',
    options: ['Noah questioned everything', 'Noah did all that God commanded him', 'Noah delayed until signs appeared', 'Noah modified the plan'],
    correctIndex: 1,
    explanation: 'Genesis emphasizes Noah\'s obedient compliance with God\'s commands.',
    difficulty: 'hard',
  },
  {
    id: '101',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Who entered the ark with Noah?',
    options: ['Noah alone', 'Noah and his wife only', 'Noah, his wife, his sons, and their wives', 'All people'],
    correctIndex: 2,
    explanation: 'Genesis 7 lists Noah\'s immediate family entering the ark.',
    difficulty: 'easy',
  },
  {
    id: '102',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How many days did rain fall during the flood?',
    options: ['30 days', '40 days and 40 nights', '70 days', '120 days'],
    correctIndex: 1,
    explanation: 'The rain fell for forty days and forty nights.',
    difficulty: 'easy',
  },
  {
    id: '103',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did Noah first send out from the ark to check the waters?',
    options: ['A dove', 'An eagle', 'A raven', 'A sparrow'],
    correctIndex: 2,
    explanation: 'Noah first sent a raven, then later sent doves.',
    difficulty: 'easy',
  },
  {
    id: '104',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did the dove bring back to Noah as a sign?',
    options: ['A branch of cedar', 'A fresh olive leaf', 'A piece of vine', 'A fig leaf'],
    correctIndex: 1,
    explanation: 'The dove returned with an olive leaf, showing waters had receded.',
    difficulty: 'easy',
  },
  {
    id: '105',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What sign did God give for His covenant after the flood?',
    options: ['Rainbow', 'Pillar of cloud', 'Star', 'Fire on altar'],
    correctIndex: 0,
    explanation: 'God set the rainbow in the clouds as covenant sign.',
    difficulty: 'easy',
  },
  {
    id: '106',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Why did God tell Noah to take seven pairs of some animals?',
    options: ['To populate distant lands', 'For clean animals and birds, including sacrifice', 'To trade later', 'To feed predators'],
    correctIndex: 1,
    explanation: 'Genesis 7 distinguishes clean animals and birds, used for worship and survival.',
    difficulty: 'medium',
  },
  {
    id: '107',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What does the phrase "God remembered Noah" indicate in Genesis 8?',
    options: ['God had forgotten', 'God acted faithfully according to covenant mercy', 'Noah prayed loudly', 'The flood ended naturally'],
    correctIndex: 1,
    explanation: 'In Scripture, "remembered" often means God moves to act on His promises.',
    difficulty: 'medium',
  },
  {
    id: '108',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'On which mountains did the ark come to rest?',
    options: ['Ararat', 'Sinai', 'Carmel', 'Zion'],
    correctIndex: 0,
    explanation: 'The ark rested on the mountains of Ararat.',
    difficulty: 'medium',
  },
  {
    id: '109',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What was Noah\'s first major act after leaving the ark?',
    options: ['Built a city', 'Planted wheat', 'Built an altar and offered burnt offerings', 'Crowned his sons'],
    correctIndex: 2,
    explanation: 'Noah worshiped by building an altar and offering sacrifices.',
    difficulty: 'medium',
  },
  {
    id: '110',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What promise did God make about the earth\'s cycles after the flood?',
    options: ['No winters', 'Seedtime and harvest shall not cease while earth remains', 'No storms', 'Permanent spring'],
    correctIndex: 1,
    explanation: 'God promised regular seasons and rhythms would continue.',
    difficulty: 'medium',
  },
  {
    id: '111',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What new permission regarding food is given in Genesis 9?',
    options: ['Only fruit allowed', 'Humans may eat moving creatures, with restrictions', 'No plants allowed', 'Fasting required'],
    correctIndex: 1,
    explanation: 'God permits meat, but forbids consuming blood.',
    difficulty: 'medium',
  },
  {
    id: '112',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What restriction accompanies eating meat in Genesis 9?',
    options: ['Only birds may be eaten', 'Do not eat flesh with its lifeblood', 'Only cooked meat', 'Only at festivals'],
    correctIndex: 1,
    explanation: 'The text forbids eating blood, associated with life.',
    difficulty: 'medium',
  },
  {
    id: '113',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What principle of justice is stated concerning human bloodshed?',
    options: ['Bloodshed is ignored', 'Whoever sheds human blood, by humans shall their blood be shed', 'Only fines apply', 'Only exile applies'],
    correctIndex: 1,
    explanation: 'Genesis 9 grounds justice in humans being made in God\'s image.',
    difficulty: 'medium',
  },
  {
    id: '114',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'With whom did God establish His covenant sign of the rainbow?',
    options: ['Noah only', 'Noah and all living creatures', 'Noah and kings only', 'Noah and priests only'],
    correctIndex: 1,
    explanation: 'The covenant extends to Noah\'s descendants and every living creature.',
    difficulty: 'medium',
  },
  {
    id: '115',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Which son acted disrespectfully when Noah was uncovered in his tent?',
    options: ['Shem', 'Japheth', 'Ham', 'Canaan'],
    correctIndex: 2,
    explanation: 'Ham saw his father\'s nakedness and told his brothers.',
    difficulty: 'medium',
  },
  {
    id: '116',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How does the flood narrative portray divine judgment and mercy together?',
    options: ['Judgment only with no mercy', 'Mercy only with no judgment', 'Judgment on corruption while preserving life through Noah', 'Neutral natural disaster'],
    correctIndex: 2,
    explanation: 'God judges violence yet provides a path of rescue through the ark.',
    difficulty: 'hard',
  },
  {
    id: '117',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What does the ark typologically suggest in biblical theology?',
    options: ['Human engineering alone saves', 'A means of salvation through obedient faith', 'Escape from moral responsibility', 'Political reform'],
    correctIndex: 1,
    explanation: 'The ark functions as God-provided refuge received by faith and obedience.',
    difficulty: 'hard',
  },
  {
    id: '118',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Why is the phrase "all flesh" significant in the flood account?',
    options: ['It limits judgment to one tribe', 'It underscores universal scope of corruption and judgment', 'It excludes animals', 'It refers only to kings'],
    correctIndex: 1,
    explanation: 'The phrase highlights the broad human and creaturely impact.',
    difficulty: 'hard',
  },
  {
    id: '119',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What is the significance of God\'s post-flood blessing to "be fruitful and multiply"?',
    options: ['A repeal of creation', 'A renewal of creation mandate after judgment', 'A command only to Noah', 'A punishment'],
    correctIndex: 1,
    explanation: 'It echoes Genesis 1, signaling continuity of God\'s purposes.',
    difficulty: 'hard',
  },
  {
    id: '120',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How is human dignity grounded in Genesis 9:6?',
    options: ['By social status', 'By image-bearing before God', 'By military strength', 'By age'],
    correctIndex: 1,
    explanation: 'The prohibition of murder is tied to humans made in God\'s image.',
    difficulty: 'hard',
  },
  {
    id: '121',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What does the rainbow primarily function as in the text?',
    options: ['Decoration', 'Sign of covenant remembrance and restraint of global flood judgment', 'Astronomical marker only', 'Warning of immediate storms'],
    correctIndex: 1,
    explanation: 'The rainbow is explicitly named as covenant sign tied to God\'s promise.',
    difficulty: 'hard',
  },
  {
    id: '122',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What ethical contrast is shown by Shem and Japheth toward Noah?',
    options: ['Open mockery', 'Covering their father with honor and discretion', 'Public accusation', 'Indifference'],
    correctIndex: 1,
    explanation: 'They walk backward and cover Noah, preserving his dignity.',
    difficulty: 'hard',
  },
  {
    id: '123',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Why is Noah\'s vineyard episode significant after the flood?',
    options: ['It proves perfect human renewal', 'It shows sin persists even after judgment and new beginnings', 'It replaces covenant promises', 'It ends genealogy'],
    correctIndex: 1,
    explanation: 'The narrative shows post-flood humanity still marked by moral failure.',
    difficulty: 'hard',
  },
  {
    id: '124',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What broader theme is reinforced by the flood story in relation to Genesis 1?',
    options: ['Creation is accidental', 'God de-creates and re-creates with order and purpose', 'Humans replace God', 'Chaos wins permanently'],
    correctIndex: 1,
    explanation: 'Waters of judgment and renewed mandate mirror creation themes.',
    difficulty: 'hard',
  },
  {
    id: '125',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What does Noah\'s obedience before visible rain demonstrate?',
    options: ['Strategic planning only', 'Faith in God\'s word before circumstances confirm it', 'Fear of neighbors', 'Desire for power'],
    correctIndex: 1,
    explanation: 'Noah acts on God\'s warning in trust before seeing fulfillment.',
    difficulty: 'hard',
  },
  {
    id: '126',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What is Genesis 10 commonly called?',
    options: ['Book of Kings', 'Table of Nations', 'Song of Moses', 'Law of Noah'],
    correctIndex: 1,
    explanation: 'Genesis 10 lists descendants of Noah and nations from them.',
    difficulty: 'easy',
  },
  {
    id: '127',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How many languages did humanity originally have at Babel?',
    options: ['Many', 'Two', 'One', 'Seventy'],
    correctIndex: 2,
    explanation: 'Genesis 11 begins by saying the whole earth had one language.',
    difficulty: 'easy',
  },
  {
    id: '128',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'In what region did people settle to build the city and tower?',
    options: ['Ararat', 'Shinar', 'Canaan', 'Edom'],
    correctIndex: 1,
    explanation: 'The builders settled in the land of Shinar.',
    difficulty: 'easy',
  },
  {
    id: '129',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What name was given to the city where languages were confused?',
    options: ['Ur', 'Nineveh', 'Babel', 'Hebron'],
    correctIndex: 2,
    explanation: 'It was called Babel because there the LORD confused language.',
    difficulty: 'easy',
  },
  {
    id: '130',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'From which son of Noah did Abram\'s line come?',
    options: ['Ham', 'Shem', 'Japheth', 'Canaan'],
    correctIndex: 1,
    explanation: 'Genesis traces the line from Shem to Terah and then Abram.',
    difficulty: 'easy',
  },
  {
    id: '131',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What repeated pattern structures Genesis 10 nation lists?',
    options: ['By military rank', 'By clans, languages, lands, and nations', 'By temple offices', 'By alphabet'],
    correctIndex: 1,
    explanation: 'The chapter repeatedly groups peoples by these descriptors.',
    difficulty: 'medium',
  },
  {
    id: '132',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who is introduced as a mighty man and kingdom founder in Genesis 10?',
    options: ['Peleg', 'Nimrod', 'Eber', 'Joktan'],
    correctIndex: 1,
    explanation: 'Nimrod is described as a mighty hunter and early ruler.',
    difficulty: 'medium',
  },
  {
    id: '133',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What building material did Babel\'s builders use instead of stone?',
    options: ['Wood planks', 'Baked bricks', 'Bronze plates', 'Marble'],
    correctIndex: 1,
    explanation: 'They said, "Come, let us make bricks and burn them thoroughly."',
    difficulty: 'medium',
  },
  {
    id: '134',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What did the people seek to make for themselves at Babel?',
    options: ['A covenant', 'A name', 'A temple law', 'A sacrifice'],
    correctIndex: 1,
    explanation: 'Their goal included making a name for themselves.',
    difficulty: 'medium',
  },
  {
    id: '135',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What fear motivated Babel\'s centralized project?',
    options: ['Fear of flood', 'Fear of being scattered over the earth', 'Fear of famine', 'Fear of wild animals'],
    correctIndex: 1,
    explanation: 'They explicitly feared being dispersed across the earth.',
    difficulty: 'medium',
  },
  {
    id: '136',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How does Genesis depict the LORD\'s response to Babel?',
    options: ['He ignored it', 'He came down to see the city and tower', 'He sent fire immediately', 'He praised their unity'],
    correctIndex: 1,
    explanation: 'The narrative says the LORD came down to inspect their work.',
    difficulty: 'medium',
  },
  {
    id: '137',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What direct action did God take to halt Babel\'s project?',
    options: ['Destroyed all tools', 'Confused their language', 'Removed the tower foundation', 'Sent drought'],
    correctIndex: 1,
    explanation: 'Language confusion stopped coordinated building.',
    difficulty: 'medium',
  },
  {
    id: '138',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What was the result of language confusion at Babel?',
    options: ['One empire formed', 'People were scattered over the face of all the earth', 'Everyone returned to Eden', 'The flood returned'],
    correctIndex: 1,
    explanation: 'God scattered humanity, ending their centralized rebellion.',
    difficulty: 'medium',
  },
  {
    id: '139',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who was Abram\'s father according to Genesis 11?',
    options: ['Nahor', 'Terah', 'Haran', 'Shem'],
    correctIndex: 1,
    explanation: 'Genesis 11 identifies Terah as father of Abram, Nahor, and Haran.',
    difficulty: 'medium',
  },
  {
    id: '140',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'From which city did Terah begin his journey with Abram\'s family?',
    options: ['Babel', 'Ur of the Chaldeans', 'Haran', 'Jerusalem'],
    correctIndex: 1,
    explanation: 'They set out from Ur and later settled in Haran.',
    difficulty: 'medium',
  },
  {
    id: '141',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How does Babel function as a theological critique of human pride?',
    options: ['It celebrates self-made glory', 'It exposes autonomous self-exaltation in defiance of God\'s mandate', 'It promotes faithful scattering', 'It abolishes judgment'],
    correctIndex: 1,
    explanation: 'Babel highlights humanity seeking glory apart from submission to God.',
    difficulty: 'hard',
  },
  {
    id: '142',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What irony is present in the phrase "the LORD came down" to see the tower?',
    options: ['The tower was too small to reach heaven despite human boasting', 'God could not find them', 'The tower had collapsed', 'The people had moved away'],
    correctIndex: 0,
    explanation: 'Human claims of greatness are undercut by God needing to "come down."',
    difficulty: 'hard',
  },
  {
    id: '143',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How do Genesis 10 and 11 together explain the nations?',
    options: ['Chapter 10 gives theological cause; chapter 11 gives list only', 'Chapter 10 gives dispersion overview; chapter 11 zooms into Babel event', 'They contradict each other', 'They describe different worlds'],
    correctIndex: 1,
    explanation: 'The chapters are complementary: one broad table, one focused narrative.',
    difficulty: 'hard',
  },
  {
    id: '144',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Why is the transition from Babel to Abram significant in Genesis?',
    options: ['It shifts from rebellion of many to God\'s redemptive call through one family', 'It ends covenant themes', 'It returns to Eden geography', 'It removes nation themes'],
    correctIndex: 0,
    explanation: 'After global rebellion, God initiates a redemptive line through Abram.',
    difficulty: 'hard',
  },
  {
    id: '145',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What does the Babel narrative reveal about unity without godliness?',
    options: ['Unity guarantees righteousness', 'Unity can magnify collective rebellion', 'Unity is always condemned', 'Unity is irrelevant to ethics'],
    correctIndex: 1,
    explanation: 'Cooperation itself is not enough when directed against God\'s purposes.',
    difficulty: 'hard',
  },
  {
    id: '146',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How does Babel connect to God\'s earlier command to fill the earth?',
    options: ['It obeys the command fully', 'It resists scattering, opposing God\'s design for humanity', 'It predates the command', 'It replaces the command with sacrifice'],
    correctIndex: 1,
    explanation: 'Their attempt to avoid dispersion conflicts with creation mandate.',
    difficulty: 'hard',
  },
  {
    id: '147',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What literary effect does the genealogy in Genesis 11:10-26 provide?',
    options: ['Interrupts all storyline', 'Bridges primeval history to patriarchal history', 'Repeats Cain\'s line only', 'Eliminates covenant focus'],
    correctIndex: 1,
    explanation: 'The genealogy links Shem\'s line to Abram, advancing the narrative.',
    difficulty: 'hard',
  },
  {
    id: '148',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'In biblical theology, Babel is often contrasted with which New Testament event?',
    options: ['Transfiguration', 'Pentecost', 'Resurrection', 'Ascension'],
    correctIndex: 1,
    explanation: 'At Pentecost, diverse languages hear one gospel message by the Spirit.',
    difficulty: 'hard',
  },
  {
    id: '149',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What does the phrase "make a name for ourselves" most clearly indicate?',
    options: ['Desire for faithful witness', 'Self-glorification independent of God', 'Concern for family lineage', 'Need for legal identity'],
    correctIndex: 1,
    explanation: 'The phrase reveals ambition centered on human fame rather than divine honor.',
    difficulty: 'hard',
  },
  {
    id: '150',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What major biblical theme continues from Genesis 10-11 into later Scripture?',
    options: ['God abandons nations permanently', 'God remains sovereign over nations and advances redemption through chosen lineage', 'Human empires replace covenant promises', 'Language differences end revelation'],
    correctIndex: 1,
    explanation: 'Genesis sets both the reality of nations and God\'s sovereign redemptive plan.',
    difficulty: 'hard',
  },
];

function getMixedQuestions(segmentId: string): Question[] {
  const all = mockQuestions.filter(q => q.segmentId === segmentId);
  const easy = all.filter(q => q.difficulty === 'easy');
  const medium = all.filter(q => q.difficulty === 'medium');
  const hard = all.filter(q => q.difficulty === 'hard');

  const shuffledEasy = shuffleArray(easy).slice(0, 5);
  const shuffledMedium = shuffleArray(medium).slice(0, 5);
  const shuffledHard = shuffleArray(hard).slice(0, 5);

  let selected = [...shuffledEasy, ...shuffledMedium, ...shuffledHard];

  if (selected.length < 15) {
    const takenIds = new Set(selected.map(q => q.id));
    const remaining = all.filter(q => !takenIds.has(q.id));
    const shuffledRemaining = shuffleArray(remaining);
    const needed = 15 - selected.length;
    selected = selected.concat(shuffledRemaining.slice(0, needed));
  }

  return shuffleArray(selected);
}

export function getQuestions(segmentId: string, difficulty: string): Question[] {
  if (difficulty === 'mixed') {
    return getMixedQuestions(segmentId);
  }

  const filtered = mockQuestions.filter(q => q.segmentId === segmentId);

  if (filtered.length === 0) {
    return [];
  }

  const byDifficulty = filtered.filter(q => q.difficulty === difficulty);

  if (byDifficulty.length >= 5) {
    return shuffleArray(byDifficulty).slice(0, 5);
  }

  // Fallback to other difficulties
  const otherDifficulties = ['easy', 'medium', 'hard'].filter(d => d !== difficulty);
  let additional: Question[] = [];

  for (const diff of otherDifficulties) {
    const more = filtered.filter(q => q.difficulty === diff);
    additional = additional.concat(more);
    if (additional.length >= 5) break;
  }

  const combined = byDifficulty.concat(additional);
  return shuffleArray(combined).slice(0, 5);
}
