export type Question = {
  id: string;
  segmentId: string;
  reference: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

function shuffleArray<T>(array: T[]): T[] {
  return [...array].sort(() => Math.random() - 0.5);
}

let usedQuestionIds: string[] = [];

const mockQuestions: Question[] = [
  {
    id: '1',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the first day?',
    options: ['Light', 'Earth', 'Heaven', 'Water'],
    correctIndex: 0,
    explanation: 'On the first day, God created light and separated it from darkness.',
    difficulty: 'easy',
  },
  {
    id: '2',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the second day?',
    options: ['Firmament', 'Sun and Moon', 'Sea creatures', 'Land'],
    correctIndex: 0,
    explanation: 'On the second day, God created the firmament to separate waters above and below.',
    difficulty: 'easy',
  },
  {
    id: '3',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the third day?',
    options: ['Dry land and vegetation', 'Fish and birds', 'Animals', 'Humans'],
    correctIndex: 0,
    explanation: 'On the third day, God gathered the waters to reveal dry land and caused vegetation to grow.',
    difficulty: 'easy',
  },
  {
    id: '4',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fourth day?',
    options: ['Sun, Moon, and stars', 'Trees and plants', 'Birds', 'Sea creatures'],
    correctIndex: 0,
    explanation: 'On the fourth day, God created the sun, moon, and stars to govern day and night.',
    difficulty: 'medium',
  },
  {
    id: '5',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fifth day?',
    options: ['Sea creatures and birds', 'Humans', 'Land animals', 'Vegetation'],
    correctIndex: 0,
    explanation: 'On the fifth day, God created sea creatures and birds to fill the waters and sky.',
    difficulty: 'medium',
  },
  {
    id: '6',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the sixth day?',
    options: ['Land animals and humans', 'Fish', 'Plants', 'Stars'],
    correctIndex: 0,
    explanation: 'On the sixth day, God created land animals and humans in His image.',
    difficulty: 'easy',
  },
  {
    id: '7',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do on the seventh day?',
    options: ['Rested', 'Created more light', 'Made the sea', 'Planted trees'],
    correctIndex: 0,
    explanation: 'On the seventh day, God rested from His work of creation.',
    difficulty: 'easy',
  },
  {
    id: '8',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the first thing God called "good"?',
    options: ['Light', 'Firmament', 'Dry land', 'Sun'],
    correctIndex: 0,
    explanation: 'After creating light on the first day, God saw that it was good.',
    difficulty: 'medium',
  },
  {
    id: '9',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create the dry land?',
    options: ['Gathered the waters', 'Spoke it into existence', 'Formed it from clay', 'Brought it from another place'],
    correctIndex: 0,
    explanation: 'God gathered the waters together to allow the dry land to appear.',
    difficulty: 'medium',
  },
  {
    id: '10',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created to fill the waters and the sky?',
    options: ['Sea creatures and birds', 'Land animals', 'Humans', 'Plants'],
    correctIndex: 0,
    explanation: 'On the fifth day, God blessed the sea creatures and birds to be fruitful and multiply.',
    difficulty: 'easy',
  },
  {
    id: '11',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which of creation was made before the sun and moon?',
    options: ['Light', 'Plants', 'Fish', 'Humans'],
    correctIndex: 0,
    explanation: 'Light was created on the first day before the sun and moon on the fourth day.',
    difficulty: 'medium',
  },
  {
    id: '12',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What role did God give to fish and birds?',
    options: ['Be fruitful and multiply', 'Rule the earth', 'Guard Eden', 'Worship'],
    correctIndex: 0,
    explanation: 'God blessed the fish and birds to be fruitful and multiply and fill the waters and sky.',
    difficulty: 'hard',
  },
  {
    id: '13',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which two humans are introduced in Genesis 2 and 3?',
    options: ['Adam and Eve', 'Noah and Sarah', 'Abraham and Lot', 'Isaac and Rebekah'],
    correctIndex: 0,
    explanation: 'Adam and Eve are the first humans in Genesis 2 and 3.',
    difficulty: 'easy',
  },
  {
    id: '14',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Where did God place Adam and Eve after creation?',
    options: ['Garden of Eden', 'Mount Sinai', 'Jerusalem', 'Nile River'],
    correctIndex: 0,
    explanation: 'God placed them in the Garden of Eden in Genesis chapter 2.',
    difficulty: 'easy',
  },
  {
    id: '15',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What instruction was given to Adam about the tree of knowledge?',
    options: ['Do not eat its fruit', 'Share fruit with others', 'Water it daily', 'Build a fence around it'],
    correctIndex: 0,
    explanation: 'God commanded Adam not to eat from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '16',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Who tempted Eve to eat the forbidden fruit?',
    options: ['The serpent', 'An angel', 'Adam', 'A neighbor'],
    correctIndex: 0,
    explanation: 'A serpent tempted Eve to eat the fruit from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '17',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the consequence for Adam after the fall?',
    options: ['Toil and work the ground', 'Flying', 'Immortality', 'Speak new languages'],
    correctIndex: 0,
    explanation: 'After the fall, Adam was told he would toil and work the ground for food.',
    difficulty: 'hard',
  },
  {
    id: '18',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What consequences did Eve receive after disobedience?',
    options: ['Increased pain in childbirth', 'Longer life', 'Ruler over Adam', 'Freedom from work'],
    correctIndex: 0,
    explanation: 'God told Eve childbirth would be painful and childbearing would involve sorrow.',
    difficulty: 'hard',
  },
  {
    id: '19',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God place at the east of Eden after the fall?',
    options: ['Cherubim and flame', 'An angelic choir', 'A golden crown', 'A waterfall'],
    correctIndex: 0,
    explanation: 'God placed cherubim and a flaming sword to guard the way to the tree of life.',
    difficulty: 'hard',
  },
  {
    id: '20',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the first human relationship described in Genesis 2?',
    options: ['Man and wife', 'Father and son', 'Teacher and student', 'King and servant'],
    correctIndex: 0,
    explanation: 'Genesis 2 describes the creation of woman as a companion for man.',
    difficulty: 'medium',
  },
  {
    id: '21',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God use to create Eve?',
    options: ['A rib from Adam', 'Dust from the ground', 'Water from the river', 'A branch from the tree'],
    correctIndex: 0,
    explanation: 'God took a rib from Adam and formed Eve as his companion.',
    difficulty: 'medium',
  },
  {
    id: '22',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the name of the garden where Adam and Eve lived?',
    options: ['Garden of Eden', 'Garden of Gethsemane', 'Garden of Olives', 'Garden of Paradise'],
    correctIndex: 0,
    explanation: 'God planted the Garden of Eden in the east and placed Adam and Eve there.',
    difficulty: 'easy',
  },
  {
    id: '23',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent promise Eve if she ate the fruit?',
    options: ['Eyes would be opened, become like God', 'Eternal life', 'Power over animals', 'Wisdom without consequences'],
    correctIndex: 0,
    explanation: 'The serpent deceived Eve by saying eating the fruit would make her like God, knowing good and evil.',
    difficulty: 'hard',
  },
  {
    id: '24',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve do after eating the forbidden fruit?',
    options: ['Hid from God', 'Celebrated', 'Told the serpent', 'Ate more fruit'],
    correctIndex: 0,
    explanation: 'When they heard God walking, Adam and Eve hid among the trees of the garden.',
    difficulty: 'medium',
  },
  {
    id: '25',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve after the fall?',
    options: ['Garments of skin', 'Crowns of gold', 'Shoes of leather', 'Houses of wood'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and Eve to clothe their nakedness.',
    difficulty: 'hard',
  },
  {
    id: '26',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How many days did God take to create the world?',
    options: ['6 days', '7 days', '5 days', '8 days'],
    correctIndex: 0,
    explanation: 'God created the heavens and the earth in six days and rested on the seventh.',
    difficulty: 'medium',
  },
  {
    id: '27',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the tree called that Adam and Eve were forbidden to eat from?',
    options: ['Tree of the knowledge of good and evil', 'Tree of life', 'Tree of wisdom', 'Tree of fruit'],
    correctIndex: 0,
    explanation: 'God commanded them not to eat from the tree of the knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '28',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the serpent would eat after the fall?',
    options: ['Dust', 'Fruit', 'Grass', 'Other serpents'],
    correctIndex: 0,
    explanation: 'God cursed the serpent to crawl on its belly and eat dust all the days of its life.',
    difficulty: 'hard',
  },
  {
    id: '29',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the order of creation on the first three days?',
    options: ['Light, firmament, dry land and plants', 'Plants, light, firmament', 'Dry land, light, firmament', 'Firmament, light, plants'],
    correctIndex: 0,
    explanation: 'Day 1: light; Day 2: firmament; Day 3: dry land and vegetation.',
    difficulty: 'hard',
  },
  {
    id: '30',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created on the fourth, fifth, and sixth days?',
    options: ['Lights, sea creatures and birds, land animals and humans', 'Humans, birds, lights', 'Birds, lights, sea creatures', 'Land animals, humans, lights'],
    correctIndex: 0,
    explanation: 'Day 4: sun/moon/stars; Day 5: sea creatures/birds; Day 6: land animals/humans.',
    difficulty: 'hard',
  },
  {
    id: '31',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'On which day did God rest from all His work?',
    options: ['Sixth day', 'Seventh day', 'First day', 'Eighth day'],
    correctIndex: 1,
    explanation: 'Genesis states that God rested on the seventh day from all His work.',
    difficulty: 'medium',
  },
  {
    id: '32',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say about all His creation?',
    options: ['It was very good', 'It was good', 'It was excellent', 'It was perfect'],
    correctIndex: 0,
    explanation: 'After creating humans, God saw everything that He had made, and it was very good.',
    difficulty: 'medium',
  },
  {
    id: '33',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s first task in the garden?',
    options: ['To work and keep the garden', 'To name the animals', 'To build a house', 'To plant trees'],
    correctIndex: 0,
    explanation: 'God put Adam in the garden to work it and keep it.',
    difficulty: 'hard',
  },
  {
    id: '34',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Eve say the serpent told her about the fruit?',
    options: ['We will not surely die', 'It will make us sick', 'It will give us power', 'It will make us happy'],
    correctIndex: 0,
    explanation: 'Eve told God that the serpent said they would not surely die if they ate the fruit.',
    difficulty: 'hard',
  },
  {
    id: '35',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do to the ground because of Adam\'s sin?',
    options: ['Cursed it with thorns and thistles', 'Made it fertile', 'Flooded it', 'Burned it'],
    correctIndex: 0,
    explanation: 'Because of Adam, the ground was cursed and would produce thorns and thistles.',
    difficulty: 'hard',
  },
  // New medium questions
  {
    id: '36',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the purpose of the firmament created on the second day?',
    options: ['To separate waters above and below', 'To hold the stars', 'To provide light', 'To support land'],
    correctIndex: 0,
    explanation: 'The firmament divided the waters that were under it from the waters above it.',
    difficulty: 'medium',
  },
  {
    id: '37',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'On which day did God create vegetation?',
    options: ['First day', 'Second day', 'Third day', 'Fourth day'],
    correctIndex: 2,
    explanation: 'Genesis 1 places the creation of vegetation on the third day.',
    difficulty: 'medium',
  },
  {
    id: '38',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What blessing did God give to sea creatures and birds?',
    options: ['Be fruitful and multiply', 'Rule over the earth', 'Live forever', 'Speak languages'],
    correctIndex: 0,
    explanation: 'God blessed them to be fruitful, multiply, and fill the seas and skies.',
    difficulty: 'medium',
  },
  {
    id: '39',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create man according to Genesis 1?',
    options: ['In His image and likeness', 'From clay', 'From a tree', 'From water'],
    correctIndex: 0,
    explanation: 'God said, "Let us make mankind in our image, in our likeness."',
    difficulty: 'medium',
  },
  {
    id: '40',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God give humans dominion over?',
    options: ['Fish, birds, livestock, and earth', 'Angels', 'God Himself', 'Each other'],
    correctIndex: 0,
    explanation: 'God gave humans rule over the fish, birds, livestock, and all the earth.',
    difficulty: 'medium',
  },
  {
    id: '41',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s role in naming the animals?',
    options: ['To see if there was a suitable helper', 'To count them', 'To feed them', 'To hunt them'],
    correctIndex: 0,
    explanation: 'God brought animals to Adam to name them and find a companion.',
    difficulty: 'medium',
  },
  {
    id: '42',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say was "not good" in Genesis 2?',
    options: ['The garden was too small', 'That man should be alone', 'That animals were many', 'That rivers flowed from Eden'],
    correctIndex: 1,
    explanation: 'God said it was not good for the man to be alone before creating the woman.',
    difficulty: 'medium',
  },
  {
    id: '43',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What trees were in the midst of the garden?',
    options: ['Tree of life and tree of knowledge', 'Tree of wisdom and tree of fruit', 'Tree of good and tree of evil', 'Tree of peace and tree of war'],
    correctIndex: 0,
    explanation: 'The tree of life and the tree of the knowledge of good and evil were in the garden.',
    difficulty: 'medium',
  },
  {
    id: '44',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent question Eve about?',
    options: ['God\'s command regarding the tree', 'The garden\'s location', 'Adam\'s name', 'The weather'],
    correctIndex: 0,
    explanation: 'The serpent asked Eve about what God had said concerning eating from the tree.',
    difficulty: 'medium',
  },
  {
    id: '45',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did Eve respond to the serpent\'s temptation?',
    options: ['She ate the fruit and gave some to Adam', 'She refused', 'She told God', 'She ran away'],
    correctIndex: 0,
    explanation: 'Eve took the fruit, ate it, and gave some to Adam who was with her.',
    difficulty: 'medium',
  },
  {
    id: '46',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve realize after eating the fruit?',
    options: ['They were naked', 'They were hungry', 'They were tired', 'They were happy'],
    correctIndex: 0,
    explanation: 'Their eyes were opened, and they knew they were naked.',
    difficulty: 'medium',
  },
  {
    id: '47',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God ask Adam when He confronted him?',
    options: ['Where are you?', 'What have you done?', 'Why did you eat?', 'Who told you?'],
    correctIndex: 0,
    explanation: 'God called to Adam and asked, "Where are you?"',
    difficulty: 'medium',
  },
  {
    id: '48',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s response to God\'s question?',
    options: ['I heard you and hid because I was naked', 'I ate the fruit', 'The serpent made me', 'I don\'t know'],
    correctIndex: 0,
    explanation: 'Adam admitted he hid because he was afraid due to his nakedness.',
    difficulty: 'medium',
  },
  {
    id: '49',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What curse did God place on the serpent?',
    options: ['Crawl on belly and eat dust', 'Lose its voice', 'Die immediately', 'Become invisible'],
    correctIndex: 0,
    explanation: 'The serpent was cursed to crawl on its belly and eat dust.',
    difficulty: 'medium',
  },
  {
    id: '50',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What enmity did God put between the serpent and the woman?',
    options: ['Between offspring', 'Between bodies', 'Between minds', 'Between homes'],
    correctIndex: 0,
    explanation: 'God put enmity between the serpent\'s offspring and the woman\'s offspring.',
    difficulty: 'medium',
  },
  {
    id: '51',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the woman\'s desire would be?',
    options: ['For her husband', 'For the garden', 'For the fruit', 'For the serpent'],
    correctIndex: 0,
    explanation: 'God said the woman\'s desire would be for her husband, and he would rule over her.',
    difficulty: 'medium',
  },
  {
    id: '52',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What name did Adam give to Eve?',
    options: ['Woman, because she was taken from man', 'Eve, because she was the mother of all living', 'Helper, because she helped him', 'Companion, because she was his friend'],
    correctIndex: 0,
    explanation: 'Adam called his wife\'s name Woman, for she was taken out of Man.',
    difficulty: 'medium',
  },
  {
    id: '53',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve to wear?',
    options: ['Garments of skin', 'Leaves', 'Animal fur', 'Cloth'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and his wife and clothed them.',
    difficulty: 'medium',
  },
  {
    id: '54',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which tree did God prevent humans from eating after the fall?',
    options: ['Tree of life', 'Tree of figs', 'Tree of cedar', 'Tree of myrrh'],
    correctIndex: 0,
    explanation: 'God sent them out and guarded the way to the tree of life.',
    difficulty: 'medium',
  },
  {
    id: '55',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What guarded the way to the tree of life?',
    options: ['Cherubim and a flaming sword', 'Angels and a wall', 'Animals and thorns', 'God Himself'],
    correctIndex: 0,
    explanation: 'Cherubim and a flaming sword flashing back and forth guarded the way.',
    difficulty: 'medium',
  },
  // New hard questions
  {
    id: '56',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which day did God bless and make holy?',
    options: ['Seventh day', 'Sixth day', 'First day', 'Third day'],
    correctIndex: 0,
    explanation: 'Genesis 2 says God blessed the seventh day and made it holy.',
    difficulty: 'hard',
  },
  {
    id: '57',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make on the fourth day to govern day and night?',
    options: ['Sun, moon, and stars', 'Birds and fish', 'Dry land and plants', 'Humans and animals'],
    correctIndex: 0,
    explanation: 'Genesis 1 records the greater and lesser lights and stars on day four.',
    difficulty: 'hard',
  },
  {
    id: '58',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What words did God speak before creating humanity in Genesis 1:26?',
    options: ['Let us make man in our image', 'Let there be light', 'Let the waters gather', 'Let the earth bring forth'],
    correctIndex: 0,
    explanation: 'Genesis 1:26 records God saying, "Let us make man in our image."',
    difficulty: 'hard',
  },
  {
    id: '59',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What command did God give humans in Genesis 1:28?',
    options: ['Be fruitful, multiply, fill the earth, and subdue it', 'Build a city in Shinar', 'Offer grain every day', 'Do not name animals'],
    correctIndex: 0,
    explanation: 'Genesis 1:28 gives this command directly to the man and woman.',
    difficulty: 'hard',
  },
  {
    id: '60',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which two named trees were in the midst of the garden?',
    options: ['Tree of life and tree of the knowledge of good and evil', 'Olive tree and fig tree', 'Cedar tree and cypress tree', 'Palm tree and vine'],
    correctIndex: 0,
    explanation: 'Genesis 2 names both the tree of life and the tree of knowledge in the garden.',
    difficulty: 'hard',
  },
  {
    id: '61',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent say would not happen if Eve ate the fruit?',
    options: ['She would not surely die', 'She would lose speech', 'She would become poor', 'She would forget Adam'],
    correctIndex: 0,
    explanation: 'Genesis 3:4 records the serpent saying, "You will not surely die."',
    difficulty: 'hard',
  },
  {
    id: '62',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve sew together after eating the fruit?',
    options: ['Fig leaves', 'Animal skins', 'Olive branches', 'Wool cloth'],
    correctIndex: 0,
    explanation: 'Genesis 3 says they sewed fig leaves together for coverings.',
    difficulty: 'hard',
  },
  {
    id: '63',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'By what would Adam eat bread after the fall?',
    options: ['By the sweat of his face', 'By river fish alone', 'By offerings at Eden', 'By hunting birds only'],
    correctIndex: 0,
    explanation: 'Genesis 3 says Adam would eat by the sweat of his face.',
    difficulty: 'hard',
  },
  {
    id: '64',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Between whom did God say He would put enmity in Genesis 3:15?',
    options: ['The serpent and the woman, and their offspring', 'Adam and Eve only', 'Cain and Abel', 'Noah and his sons'],
    correctIndex: 0,
    explanation: 'Genesis 3:15 directly states enmity between the serpent and the woman and their offspring.',
    difficulty: 'hard',
  },
  {
    id: '65',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God multiply for the woman after the fall?',
    options: ['Pain in childbearing', 'Length of life', 'Size of her family', 'Harvest yields'],
    correctIndex: 0,
    explanation: 'Genesis 3:16 says God would multiply the woman\'s pain in childbearing.',
    difficulty: 'hard',
  },
  {
    id: '66',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Who made garments of skin for Adam and Eve?',
    options: ['The LORD God', 'Adam', 'Eve', 'An angel'],
    correctIndex: 0,
    explanation: 'Genesis 3:21 says the LORD God made garments of skin and clothed them.',
    difficulty: 'hard',
  },
  {
    id: '67',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God place east of Eden to guard the way to the tree of life?',
    options: ['Cherubim and a flaming sword', 'A wall of stone', 'A river of fire', 'Twelve guards'],
    correctIndex: 0,
    explanation: 'Genesis 3 describes cherubim and a flaming sword guarding the tree of life.',
    difficulty: 'hard',
  },
  {
    id: '68',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What name did Adam give his wife in Genesis 3:20?',
    options: ['Eve', 'Sarah', 'Miriam', 'Leah'],
    correctIndex: 0,
    explanation: 'Adam named his wife Eve because she was mother of all living.',
    difficulty: 'hard',
  },
  {
    id: '69',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam say about the woman when she was brought to him?',
    options: ['This at last is bone of my bones and flesh of my flesh', 'She shall not eat fruit', 'She will name the animals', 'She came from the dust alone'],
    correctIndex: 0,
    explanation: 'Genesis 2 records Adam\'s words when he first saw the woman.',
    difficulty: 'hard',
  },
  {
    id: '70',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Where did God place the man after forming him from dust?',
    options: ['Garden of Eden', 'Land of Nod', 'Plain of Shinar', 'Mount Ararat'],
    correctIndex: 0,
    explanation: 'Genesis 2:8 and 2:15 say God put the man in the garden of Eden.',
    difficulty: 'hard',
  },
  {
    id: '71',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God say the serpent would move after the curse?',
    options: ['On its belly', 'On two legs', 'With wings', 'In the sea'],
    correctIndex: 0,
    explanation: 'Genesis 3:14 states the serpent would go on its belly.',
    difficulty: 'hard',
  },
  {
    id: '72',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What question did God ask the woman in Genesis 3:13?',
    options: ['What is this that you have done?', 'Where is your husband?', 'Why are you silent?', 'Who named the animals?'],
    correctIndex: 0,
    explanation: 'Genesis 3:13 records God asking the woman this exact question.',
    difficulty: 'hard',
  },
  {
    id: '73',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What would the ground produce for Adam after the curse?',
    options: ['Thorns and thistles', 'Gold and silver', 'Only wheat', 'No plants at all'],
    correctIndex: 0,
    explanation: 'God told Adam the ground would bring forth thorns and thistles.',
    difficulty: 'hard',
  },
  {
    id: '74',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God form from Adam\'s rib?',
    options: ['The woman', 'A tree', 'A river', 'A garment'],
    correctIndex: 0,
    explanation: 'Genesis 2 says God built the rib into a woman and brought her to the man.',
    difficulty: 'hard',
  },
  {
    id: '75',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'From what part of Adam did God make the woman?',
    options: ['A rib', 'His hand', 'His foot', 'His forehead'],
    correctIndex: 0,
    explanation: 'Genesis 2 states that God took one of Adam\'s ribs and made the woman.',
    difficulty: 'hard',
  },
  {
    id: '76',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who were the two sons of Adam and Eve in Genesis 4?',
    options: ['Cain and Abel', 'Shem and Ham', 'Isaac and Ishmael', 'Esau and Jacob'],
    correctIndex: 0,
    explanation: 'Genesis 4 introduces Cain and Abel as sons of Adam and Eve.',
    difficulty: 'easy',
  },
  {
    id: '77',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What was Abel\'s occupation?',
    options: ['Farmer', 'Shepherd', 'Carpenter', 'Hunter'],
    correctIndex: 1,
    explanation: 'Abel kept flocks, while Cain worked the ground.',
    difficulty: 'easy',
  },
  {
    id: '78',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What was Cain\'s occupation?',
    options: ['Worker of the ground', 'Priest', 'King', 'Fisherman'],
    correctIndex: 0,
    explanation: 'Cain is described as one who worked the soil.',
    difficulty: 'easy',
  },
  {
    id: '79',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who was killed by his brother in Genesis 4?',
    options: ['Cain', 'Abel', 'Seth', 'Enoch'],
    correctIndex: 1,
    explanation: 'Cain rose up against Abel and killed him in the field.',
    difficulty: 'easy',
  },
  {
    id: '80',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who was born to Adam and Eve after Abel\'s death?',
    options: ['Noah', 'Enosh', 'Seth', 'Lamech'],
    correctIndex: 2,
    explanation: 'Eve said God appointed Seth in place of Abel.',
    difficulty: 'easy',
  },
  {
    id: '81',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What did Abel bring as his offering?',
    options: ['Firstborn of his flock and fat portions', 'Only grain from the field', 'A drink offering of water', 'No offering at all'],
    correctIndex: 0,
    explanation: 'Genesis 4 specifies that Abel brought firstborn portions from his flock.',
    difficulty: 'medium',
  },
  {
    id: '82',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What warning did God give Cain before he sinned?',
    options: ['Leave the land', 'Sin is crouching at the door; you must rule over it', 'Offer another animal', 'Build an altar'],
    correctIndex: 1,
    explanation: 'God warned Cain that sin desired him, but he should master it.',
    difficulty: 'medium',
  },
  {
    id: '83',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How did Cain answer God when asked about Abel?',
    options: ['I buried him', 'I do not know; am I my brother\'s keeper?', 'He left the land', 'He is with Seth'],
    correctIndex: 1,
    explanation: 'Cain responded with denial and the phrase about being his brother\'s keeper.',
    difficulty: 'medium',
  },
  {
    id: '84',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What curse did Cain receive?',
    options: ['He would no longer farm', 'He would be a fugitive and wanderer', 'He would lose speech', 'He would be childless'],
    correctIndex: 1,
    explanation: 'God declared Cain would be a restless wanderer on the earth.',
    difficulty: 'medium',
  },
  {
    id: '85',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What did God place on Cain?',
    options: ['A crown', 'A mark to protect him from being killed', 'A chain', 'A scarlet robe'],
    correctIndex: 1,
    explanation: 'The mark on Cain served as protection from vengeance.',
    difficulty: 'medium',
  },
  {
    id: '86',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Where did Cain settle after leaving the LORD\'s presence?',
    options: ['Canaan', 'Shinar', 'Nod, east of Eden', 'Egypt'],
    correctIndex: 2,
    explanation: 'Genesis says Cain settled in the land of Nod, east of Eden.',
    difficulty: 'medium',
  },
  {
    id: '87',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What city did Cain build and name after his son?',
    options: ['Enoch', 'Babel', 'Ur', 'Jericho'],
    correctIndex: 0,
    explanation: 'Cain named the city after his son Enoch.',
    difficulty: 'medium',
  },
  {
    id: '88',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Which descendant of Cain is known for saying he killed a man?',
    options: ['Jabal', 'Tubal-cain', 'Lamech', 'Enosh'],
    correctIndex: 2,
    explanation: 'Lamech\'s poem records his violent boast.',
    difficulty: 'medium',
  },
  {
    id: '89',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'In Seth\'s line, what began in the days of Enosh?',
    options: ['People began to call on the name of the LORD', 'People built towers', 'People discovered bronze', 'People crossed the sea'],
    correctIndex: 0,
    explanation: 'Genesis 4:26 notes that people began calling on the LORD\'s name.',
    difficulty: 'medium',
  },
  {
    id: '90',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who is described as walking with God and then not being found?',
    options: ['Methuselah', 'Noah', 'Enoch', 'Seth'],
    correctIndex: 2,
    explanation: 'Genesis 5 says Enoch walked with God, then God took him.',
    difficulty: 'medium',
  },
  {
    id: '91',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How old was Adam when Seth was born?',
    options: ['130 years', '90 years', '365 years', '500 years'],
    correctIndex: 0,
    explanation: 'Genesis 5:3 says Adam was 130 years old when he fathered Seth.',
    difficulty: 'hard',
  },
  {
    id: '92',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How many years did Enoch live before God took him?',
    options: ['777 years', '365 years', '930 years', '120 years'],
    correctIndex: 1,
    explanation: 'Genesis 5:23 states all the days of Enoch were 365 years.',
    difficulty: 'hard',
  },
  {
    id: '93',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who was the father of Methuselah?',
    options: ['Noah', 'Enoch', 'Lamech', 'Seth'],
    correctIndex: 1,
    explanation: 'Genesis 5 lists Methuselah as son of Enoch.',
    difficulty: 'hard',
  },
  {
    id: '94',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How old was Noah when he became father of Shem, Ham, and Japheth?',
    options: ['350 years', '500 years', '600 years', '700 years'],
    correctIndex: 1,
    explanation: 'Genesis 5:32 says Noah was 500 years old and fathered his sons.',
    difficulty: 'hard',
  },
  {
    id: '95',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What did God say was filled on the earth in Genesis 6?',
    options: ['Peace', 'Violence', 'Music', 'Wisdom'],
    correctIndex: 1,
    explanation: 'Genesis 6:11 says the earth was filled with violence.',
    difficulty: 'hard',
  },
  {
    id: '96',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'Who found favor in the eyes of the LORD in Genesis 6?',
    options: ['Cain', 'Noah', 'Lamech', 'Jabal'],
    correctIndex: 1,
    explanation: 'Genesis 6:8 states that Noah found favor in the eyes of the LORD.',
    difficulty: 'hard',
  },
  {
    id: '97',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How many sons are named for Noah in Genesis 6?',
    options: ['One', 'Two', 'Three', 'Four'],
    correctIndex: 2,
    explanation: 'Genesis 6:10 names three sons: Shem, Ham, and Japheth.',
    difficulty: 'hard',
  },
  {
    id: '98',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What length did God give for the ark in cubits?',
    options: ['100 cubits', '200 cubits', '300 cubits', '500 cubits'],
    correctIndex: 2,
    explanation: 'Genesis 6:15 gives the ark length as 300 cubits.',
    difficulty: 'hard',
  },
  {
    id: '99',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'How many decks was Noah instructed to make in the ark?',
    options: ['One', 'Two', 'Three', 'Four'],
    correctIndex: 2,
    explanation: 'Genesis 6:16 says to make lower, second, and third decks.',
    difficulty: 'hard',
  },
  {
    id: '100',
    segmentId: 'genesis_4_6',
    reference: 'Genesis 4-6',
    question: 'What was Noah commanded to bring into the ark for food?',
    options: ['Only grain', 'Every sort of food that is eaten', 'Only fruit', 'Only fish'],
    correctIndex: 1,
    explanation: 'Genesis 6:21 commands Noah to gather every sort of food to store up.',
    difficulty: 'hard',
  },
  {
    id: '101',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Who entered the ark with Noah?',
    options: ['Noah alone', 'Noah and his wife only', 'Noah, his wife, his sons, and their wives', 'All people'],
    correctIndex: 2,
    explanation: 'Genesis 7 lists Noah\'s immediate family entering the ark.',
    difficulty: 'easy',
  },
  {
    id: '102',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How many days did rain fall during the flood?',
    options: ['30 days', '40 days and 40 nights', '70 days', '120 days'],
    correctIndex: 1,
    explanation: 'The rain fell for forty days and forty nights.',
    difficulty: 'easy',
  },
  {
    id: '103',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did Noah first send out from the ark to check the waters?',
    options: ['A dove', 'An eagle', 'A raven', 'A sparrow'],
    correctIndex: 2,
    explanation: 'Noah first sent a raven, then later sent doves.',
    difficulty: 'easy',
  },
  {
    id: '104',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did the dove bring back to Noah as a sign?',
    options: ['A branch of cedar', 'A fresh olive leaf', 'A piece of vine', 'A fig leaf'],
    correctIndex: 1,
    explanation: 'The dove returned with an olive leaf, showing waters had receded.',
    difficulty: 'easy',
  },
  {
    id: '105',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What sign did God give for His covenant after the flood?',
    options: ['Rainbow', 'Pillar of cloud', 'Star', 'Fire on altar'],
    correctIndex: 0,
    explanation: 'God set the rainbow in the clouds as covenant sign.',
    difficulty: 'easy',
  },
  {
    id: '106',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'According to Genesis 7, how many pairs of every clean animal was Noah to take?',
    options: ['One pair', 'Two pairs', 'Seven pairs', 'Ten pairs'],
    correctIndex: 2,
    explanation: 'Genesis 7:2 specifies seven pairs of clean animals.',
    difficulty: 'medium',
  },
  {
    id: '107',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did God send over the earth in Genesis 8 so the waters subsided?',
    options: ['A great fire', 'A wind', 'An earthquake', 'A drought'],
    correctIndex: 1,
    explanation: 'Genesis 8:1 says God made a wind blow over the earth, and the waters subsided.',
    difficulty: 'medium',
  },
  {
    id: '108',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'On which mountains did the ark come to rest?',
    options: ['Ararat', 'Sinai', 'Carmel', 'Zion'],
    correctIndex: 0,
    explanation: 'The ark rested on the mountains of Ararat.',
    difficulty: 'medium',
  },
  {
    id: '109',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What was Noah\'s first major act after leaving the ark?',
    options: ['Built a city', 'Planted wheat', 'Built an altar and offered burnt offerings', 'Crowned his sons'],
    correctIndex: 2,
    explanation: 'Noah worshiped by building an altar and offering sacrifices.',
    difficulty: 'medium',
  },
  {
    id: '110',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What promise did God make about the earth\'s cycles after the flood?',
    options: ['No winters', 'Seedtime and harvest shall not cease while earth remains', 'No storms', 'Permanent spring'],
    correctIndex: 1,
    explanation: 'God promised regular seasons and rhythms would continue.',
    difficulty: 'medium',
  },
  {
    id: '111',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What new permission regarding food is given in Genesis 9?',
    options: ['Only fruit allowed', 'Humans may eat moving creatures, with restrictions', 'No plants allowed', 'Fasting required'],
    correctIndex: 1,
    explanation: 'God permits meat, but forbids consuming blood.',
    difficulty: 'medium',
  },
  {
    id: '112',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What restriction accompanies eating meat in Genesis 9?',
    options: ['Only birds may be eaten', 'Do not eat flesh with its lifeblood', 'Only cooked meat', 'Only at festivals'],
    correctIndex: 1,
    explanation: 'The text forbids eating blood, associated with life.',
    difficulty: 'medium',
  },
  {
    id: '113',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What principle of justice is stated concerning human bloodshed?',
    options: ['Bloodshed is ignored', 'Whoever sheds human blood, by humans shall their blood be shed', 'Only fines apply', 'Only exile applies'],
    correctIndex: 1,
    explanation: 'Genesis 9 grounds justice in humans being made in God\'s image.',
    difficulty: 'medium',
  },
  {
    id: '114',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'With whom did God establish His covenant sign of the rainbow?',
    options: ['Noah only', 'Noah and all living creatures', 'Noah and kings only', 'Noah and priests only'],
    correctIndex: 1,
    explanation: 'The covenant extends to Noah\'s descendants and every living creature.',
    difficulty: 'medium',
  },
  {
    id: '115',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Which son acted disrespectfully when Noah was uncovered in his tent?',
    options: ['Shem', 'Japheth', 'Ham', 'Canaan'],
    correctIndex: 2,
    explanation: 'Ham saw his father\'s nakedness and told his brothers.',
    difficulty: 'medium',
  },
  {
    id: '116',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How high did the floodwaters rise above the highest mountains according to Genesis 7?',
    options: ['Seven cubits', 'Fifteen cubits', 'Thirty cubits', 'Fifty cubits'],
    correctIndex: 1,
    explanation: 'Genesis 7:20 states the waters prevailed fifteen cubits above the mountains.',
    difficulty: 'hard',
  },
  {
    id: '117',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'For how many days did the waters prevail on the earth?',
    options: ['40 days', '70 days', '120 days', '150 days'],
    correctIndex: 3,
    explanation: 'Genesis 7:24 says the waters prevailed for 150 days.',
    difficulty: 'hard',
  },
  {
    id: '118',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'After how many days did Noah open the window of the ark in Genesis 8?',
    options: ['7 days', '14 days', '40 days', '150 days'],
    correctIndex: 2,
    explanation: 'Genesis 8:6 says Noah opened the window after forty days.',
    difficulty: 'hard',
  },
  {
    id: '119',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How many times did Noah send out a dove from the ark?',
    options: ['One time', 'Two times', 'Three times', 'Four times'],
    correctIndex: 2,
    explanation: 'Genesis 8 records three dove releases: return, return with olive leaf, and no return.',
    difficulty: 'hard',
  },
  {
    id: '120',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How many days did Noah wait between sending out the dove each time?',
    options: ['Three days', 'Five days', 'Seven days', 'Ten days'],
    correctIndex: 2,
    explanation: 'Genesis 8:10 and 8:12 each mention waiting another seven days.',
    difficulty: 'hard',
  },
  {
    id: '121',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'With whom did God establish His covenant in Genesis 9?',
    options: ['Noah only', 'Noah and his descendants and every living creature', 'Shem only', 'Only the clean animals'],
    correctIndex: 1,
    explanation: 'Genesis 9 repeatedly states the covenant includes Noah, his offspring, and all living creatures.',
    difficulty: 'hard',
  },
  {
    id: '122',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What ethical contrast is shown by Shem and Japheth toward Noah?',
    options: ['Open mockery', 'Covering their father with honor and discretion', 'Public accusation', 'Indifference'],
    correctIndex: 1,
    explanation: 'They walk backward and cover Noah, preserving his dignity.',
    difficulty: 'hard',
  },
  {
    id: '123',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'Whom did Noah curse after learning what happened in his tent?',
    options: ['Ham', 'Canaan', 'Shem', 'Japheth'],
    correctIndex: 1,
    explanation: 'Genesis 9:25 records Noah saying, "Cursed be Canaan."',
    difficulty: 'hard',
  },
  {
    id: '124',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'What did Noah say Canaan would be to his brothers?',
    options: ['A king of kings', 'A servant of servants', 'A priest forever', 'A mighty hunter'],
    correctIndex: 1,
    explanation: 'Genesis 9:25 says, "a servant of servants shall he be to his brothers."',
    difficulty: 'hard',
  },
  {
    id: '125',
    segmentId: 'genesis_7_9',
    reference: 'Genesis 7-9',
    question: 'How many years did Noah live in total?',
    options: ['700 years', '850 years', '900 years', '950 years'],
    correctIndex: 3,
    explanation: 'Genesis 9:29 says Noah lived 950 years.',
    difficulty: 'hard',
  },
  {
    id: '126',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What is Genesis 10 commonly called?',
    options: ['Book of Kings', 'Table of Nations', 'Song of Moses', 'Law of Noah'],
    correctIndex: 1,
    explanation: 'Genesis 10 lists descendants of Noah and nations from them.',
    difficulty: 'easy',
  },
  {
    id: '127',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'How many languages did humanity originally have at Babel?',
    options: ['Many', 'Two', 'One', 'Seventy'],
    correctIndex: 2,
    explanation: 'Genesis 11 begins by saying the whole earth had one language.',
    difficulty: 'easy',
  },
  {
    id: '128',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'In what region did people settle to build the city and tower?',
    options: ['Ararat', 'Shinar', 'Canaan', 'Edom'],
    correctIndex: 1,
    explanation: 'The builders settled in the land of Shinar.',
    difficulty: 'easy',
  },
  {
    id: '129',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What name was given to the city where languages were confused?',
    options: ['Ur', 'Nineveh', 'Babel', 'Hebron'],
    correctIndex: 2,
    explanation: 'It was called Babel because there the LORD confused language.',
    difficulty: 'easy',
  },
  {
    id: '130',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'From which son of Noah did Abram\'s line come?',
    options: ['Ham', 'Shem', 'Japheth', 'Canaan'],
    correctIndex: 1,
    explanation: 'Genesis traces the line from Shem to Terah and then Abram.',
    difficulty: 'easy',
  },
  {
    id: '131',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What repeated pattern structures Genesis 10 nation lists?',
    options: ['By military rank', 'By clans, languages, lands, and nations', 'By temple offices', 'By alphabet'],
    correctIndex: 1,
    explanation: 'The chapter repeatedly groups peoples by these descriptors.',
    difficulty: 'medium',
  },
  {
    id: '132',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who is introduced as a mighty man and kingdom founder in Genesis 10?',
    options: ['Peleg', 'Nimrod', 'Eber', 'Joktan'],
    correctIndex: 1,
    explanation: 'Nimrod is described as a mighty hunter and early ruler.',
    difficulty: 'medium',
  },
  {
    id: '133',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What building material did Babel\'s builders use instead of stone?',
    options: ['Wood planks', 'Baked bricks', 'Bronze plates', 'Marble'],
    correctIndex: 1,
    explanation: 'They said, "Come, let us make bricks and burn them thoroughly."',
    difficulty: 'medium',
  },
  {
    id: '134',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What did the people seek to make for themselves at Babel?',
    options: ['A covenant', 'A name', 'A temple law', 'A sacrifice'],
    correctIndex: 1,
    explanation: 'Their goal included making a name for themselves.',
    difficulty: 'medium',
  },
  {
    id: '135',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What fear motivated Babel\'s centralized project?',
    options: ['Fear of flood', 'Fear of being scattered over the earth', 'Fear of famine', 'Fear of wild animals'],
    correctIndex: 1,
    explanation: 'They explicitly feared being dispersed across the earth.',
    difficulty: 'medium',
  },
  {
    id: '136',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What did the LORD do before confusing the language at Babel?',
    options: ['He ignored the city', 'He came down to see the city and tower', 'He flooded the plain', 'He sent an angelic army'],
    correctIndex: 1,
    explanation: 'Genesis 11 says the LORD came down to see what people built.',
    difficulty: 'medium',
  },
  {
    id: '137',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What direct action did God take to halt Babel\'s project?',
    options: ['Destroyed all tools', 'Confused their language', 'Removed the tower foundation', 'Sent drought'],
    correctIndex: 1,
    explanation: 'Language confusion stopped coordinated building.',
    difficulty: 'medium',
  },
  {
    id: '138',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What was the result of language confusion at Babel?',
    options: ['One empire formed', 'People were scattered over the face of all the earth', 'Everyone returned to Eden', 'The flood returned'],
    correctIndex: 1,
    explanation: 'God scattered humanity, ending their centralized rebellion.',
    difficulty: 'medium',
  },
  {
    id: '139',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who was Abram\'s father according to Genesis 11?',
    options: ['Nahor', 'Terah', 'Haran', 'Shem'],
    correctIndex: 1,
    explanation: 'Genesis 11 identifies Terah as father of Abram, Nahor, and Haran.',
    difficulty: 'medium',
  },
  {
    id: '140',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'From which city did Terah begin his journey with Abram\'s family?',
    options: ['Babel', 'Ur of the Chaldeans', 'Haran', 'Jerusalem'],
    correctIndex: 1,
    explanation: 'They set out from Ur and later settled in Haran.',
    difficulty: 'medium',
  },
  {
    id: '141',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What did the people say they would build in Shinar?',
    options: ['A city and a tower with its top in the heavens', 'An ark and an altar', 'A tabernacle and courtyard', 'A wall around Eden'],
    correctIndex: 0,
    explanation: 'Genesis 11:4 records their plan to build a city and a tower.',
    difficulty: 'hard',
  },
  {
    id: '142',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Where did the LORD confuse the language of all the earth?',
    options: ['Babel', 'Ur', 'Haran', 'Canaan'],
    correctIndex: 0,
    explanation: 'Genesis 11:9 says language was confused there, and the city was called Babel.',
    difficulty: 'hard',
  },
  {
    id: '143',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who was born to Shem two years after the flood?',
    options: ['Arphaxad', 'Peleg', 'Terah', 'Nahor'],
    correctIndex: 0,
    explanation: 'Genesis 11:10 states that Shem fathered Arphaxad two years after the flood.',
    difficulty: 'hard',
  },
  {
    id: '144',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Who was the father of Peleg and Joktan?',
    options: ['Eber', 'Arphaxad', 'Terah', 'Nahor'],
    correctIndex: 0,
    explanation: 'Genesis 10:25 names Eber as father of Peleg and Joktan.',
    difficulty: 'hard',
  },
  {
    id: '145',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'In which city did Terah settle before his death?',
    options: ['Ur', 'Babel', 'Haran', 'Jerusalem'],
    correctIndex: 2,
    explanation: 'Genesis 11:31-32 says Terah came to Haran and died there.',
    difficulty: 'hard',
  },
  {
    id: '146',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What was Abram\'s wife\'s name in Genesis 11?',
    options: ['Rebekah', 'Rachel', 'Sarai', 'Leah'],
    correctIndex: 2,
    explanation: 'Genesis 11:29 identifies Abram\'s wife as Sarai.',
    difficulty: 'hard',
  },
  {
    id: '147',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'Whose daughter was Milcah, wife of Nahor?',
    options: ['Terah\'s daughter', 'Haran\'s daughter', 'Shem\'s daughter', 'Abram\'s daughter'],
    correctIndex: 1,
    explanation: 'Genesis 11:29 says Milcah was the daughter of Haran.',
    difficulty: 'hard',
  },
  {
    id: '148',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What was the name of Haran\'s other daughter mentioned in Genesis 11:29?',
    options: ['Dinah', 'Iscah', 'Miriam', 'Deborah'],
    correctIndex: 1,
    explanation: 'Genesis 11:29 names Milcah and Iscah as daughters of Haran.',
    difficulty: 'hard',
  },
  {
    id: '149',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What does Genesis 11 say about Sarai having children?',
    options: ['She had many sons', 'She had one daughter', 'She was barren and had no child', 'She adopted Lot'],
    correctIndex: 2,
    explanation: 'Genesis 11:30 explicitly states that Sarai was barren and had no child.',
    difficulty: 'hard',
  },
  {
    id: '150',
    segmentId: 'genesis_10_11',
    reference: 'Genesis 10-11',
    question: 'What destination did Terah set out for when leaving Ur?',
    options: ['Egypt', 'Babel', 'Canaan', 'Edom'],
    correctIndex: 2,
    explanation: 'Genesis 11:31 says Terah set out from Ur to go to the land of Canaan.',
    difficulty: 'hard',
  },
];

function getAvailableQuestions(questions: Question[], needed: number): Question[] {
  let availableQuestions = questions.filter(q => !usedQuestionIds.includes(q.id));

  if (availableQuestions.length < needed) {
    usedQuestionIds = [];
    availableQuestions = questions;
  }

  return availableQuestions;
}

function recordUsedQuestions(questions: Question[]) {
  const selectedIds = questions.map(q => q.id);
  usedQuestionIds = [...new Set([...usedQuestionIds, ...selectedIds])];
}

function getMixedQuestions(segmentId: string): Question[] {
  const all = mockQuestions.filter(q => q.segmentId === segmentId);
  const availableQuestions = getAvailableQuestions(all, 15);
  const easy = availableQuestions.filter(q => q.difficulty === 'easy');
  const medium = availableQuestions.filter(q => q.difficulty === 'medium');
  const hard = availableQuestions.filter(q => q.difficulty === 'hard');

  const shuffledEasy = shuffleArray(easy).slice(0, 5);
  const shuffledMedium = shuffleArray(medium).slice(0, 5);
  const shuffledHard = shuffleArray(hard).slice(0, 5);

  let selected = [...shuffledEasy, ...shuffledMedium, ...shuffledHard];

  if (selected.length < 15) {
    const takenIds = new Set(selected.map(q => q.id));
    const remaining = availableQuestions.filter(q => !takenIds.has(q.id));
    const shuffledRemaining = shuffleArray(remaining);
    const needed = 15 - selected.length;
    selected = selected.concat(shuffledRemaining.slice(0, needed));
  }

  const finalSelection = shuffleArray(selected);
  recordUsedQuestions(finalSelection);

  return finalSelection;
}

export function getQuestions(segmentId: string, difficulty: string): Question[] {
  if (difficulty === 'mixed') {
    return getMixedQuestions(segmentId);
  }

  const filtered = mockQuestions.filter(q => q.segmentId === segmentId);

  if (filtered.length === 0) {
    return [];
  }

  const availableQuestions = getAvailableQuestions(filtered, 5);
  const byDifficulty = availableQuestions.filter(q => q.difficulty === difficulty);

  if (byDifficulty.length >= 5) {
    const selected = shuffleArray(byDifficulty).slice(0, 5);
    recordUsedQuestions(selected);
    return selected;
  }

  // Fallback to other difficulties
  const otherDifficulties = ['easy', 'medium', 'hard'].filter(d => d !== difficulty);
  let additional: Question[] = [];

  for (const diff of otherDifficulties) {
    const more = availableQuestions.filter(q => q.difficulty === diff);
    additional = additional.concat(more);
    if (additional.length >= 5) break;
  }

  const combined = byDifficulty.concat(additional);
  const selected = shuffleArray(combined).slice(0, 5);
  recordUsedQuestions(selected);

  return selected;
}
