export type Question = {
  id: string;
  segmentId: string;
  reference: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
};

function shuffleArray<T>(array: T[]): T[] {
  return [...array].sort(() => Math.random() - 0.5);
}

const mockQuestions: Question[] = [
  {
    id: '1',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the first day?',
    options: ['Light', 'Earth', 'Heaven', 'Water'],
    correctIndex: 0,
    explanation: 'On the first day, God created light and separated it from darkness.',
    difficulty: 'easy',
  },
  {
    id: '2',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the second day?',
    options: ['Firmament', 'Sun and Moon', 'Sea creatures', 'Land'],
    correctIndex: 0,
    explanation: 'On the second day, God created the firmament to separate waters above and below.',
    difficulty: 'easy',
  },
  {
    id: '3',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the third day?',
    options: ['Dry land and vegetation', 'Fish and birds', 'Animals', 'Humans'],
    correctIndex: 0,
    explanation: 'On the third day, God gathered the waters to reveal dry land and caused vegetation to grow.',
    difficulty: 'easy',
  },
  {
    id: '4',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fourth day?',
    options: ['Sun, Moon, and stars', 'Trees and plants', 'Birds', 'Sea creatures'],
    correctIndex: 0,
    explanation: 'On the fourth day, God created the sun, moon, and stars to govern day and night.',
    difficulty: 'medium',
  },
  {
    id: '5',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the fifth day?',
    options: ['Sea creatures and birds', 'Humans', 'Land animals', 'Vegetation'],
    correctIndex: 0,
    explanation: 'On the fifth day, God created sea creatures and birds to fill the waters and sky.',
    difficulty: 'medium',
  },
  {
    id: '6',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God create on the sixth day?',
    options: ['Land animals and humans', 'Fish', 'Plants', 'Stars'],
    correctIndex: 0,
    explanation: 'On the sixth day, God created land animals and humans in His image.',
    difficulty: 'easy',
  },
  {
    id: '7',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do on the seventh day?',
    options: ['Rested', 'Created more light', 'Made the sea', 'Planted trees'],
    correctIndex: 0,
    explanation: 'On the seventh day, God rested from His work of creation.',
    difficulty: 'easy',
  },
  {
    id: '8',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the first thing God called "good"?',
    options: ['Light', 'Firmament', 'Dry land', 'Sun'],
    correctIndex: 0,
    explanation: 'After creating light on the first day, God saw that it was good.',
    difficulty: 'medium',
  },
  {
    id: '9',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create the dry land?',
    options: ['Gathered the waters', 'Spoke it into existence', 'Formed it from clay', 'Brought it from another place'],
    correctIndex: 0,
    explanation: 'God gathered the waters together to allow the dry land to appear.',
    difficulty: 'medium',
  },
  {
    id: '10',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created to fill the waters and the sky?',
    options: ['Sea creatures and birds', 'Land animals', 'Humans', 'Plants'],
    correctIndex: 0,
    explanation: 'On the fifth day, God blessed the sea creatures and birds to be fruitful and multiply.',
    difficulty: 'easy',
  },
  {
    id: '11',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which of creation was made before the sun and moon?',
    options: ['Light', 'Plants', 'Fish', 'Humans'],
    correctIndex: 0,
    explanation: 'Light was created on the first day before the sun and moon on the fourth day.',
    difficulty: 'medium',
  },
  {
    id: '12',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What role did God give to fish and birds?',
    options: ['Be fruitful and multiply', 'Rule the earth', 'Guard Eden', 'Worship'],
    correctIndex: 0,
    explanation: 'God blessed the fish and birds to be fruitful and multiply and fill the waters and sky.',
    difficulty: 'hard',
  },
  {
    id: '13',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Which two humans are introduced in Genesis 2 and 3?',
    options: ['Adam and Eve', 'Noah and Sarah', 'Abraham and Lot', 'Isaac and Rebekah'],
    correctIndex: 0,
    explanation: 'Adam and Eve are the first humans in Genesis 2 and 3.',
    difficulty: 'easy',
  },
  {
    id: '14',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Where did God place Adam and Eve after creation?',
    options: ['Garden of Eden', 'Mount Sinai', 'Jerusalem', 'Nile River'],
    correctIndex: 0,
    explanation: 'God placed them in the Garden of Eden in Genesis chapter 2.',
    difficulty: 'easy',
  },
  {
    id: '15',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What instruction was given to Adam about the tree of knowledge?',
    options: ['Do not eat its fruit', 'Share fruit with others', 'Water it daily', 'Build a fence around it'],
    correctIndex: 0,
    explanation: 'God commanded Adam not to eat from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '16',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Who tempted Eve to eat the forbidden fruit?',
    options: ['The serpent', 'An angel', 'Adam', 'A neighbor'],
    correctIndex: 0,
    explanation: 'A serpent tempted Eve to eat the fruit from the tree of knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '17',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the consequence for Adam after the fall?',
    options: ['Toil and work the ground', 'Flying', 'Immortality', 'Speak new languages'],
    correctIndex: 0,
    explanation: 'After the fall, Adam was told he would toil and work the ground for food.',
    difficulty: 'hard',
  },
  {
    id: '18',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What consequences did Eve receive after disobedience?',
    options: ['Increased pain in childbirth', 'Longer life', 'Ruler over Adam', 'Freedom from work'],
    correctIndex: 0,
    explanation: 'God told Eve childbirth would be painful and childbearing would involve sorrow.',
    difficulty: 'hard',
  },
  {
    id: '19',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God place at the east of Eden after the fall?',
    options: ['Cherubim and flame', 'An angelic choir', 'A golden crown', 'A waterfall'],
    correctIndex: 0,
    explanation: 'God placed cherubim and a flaming sword to guard the way to the tree of life.',
    difficulty: 'hard',
  },
  {
    id: '20',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the first human relationship described in Genesis 2?',
    options: ['Man and wife', 'Father and son', 'Teacher and student', 'King and servant'],
    correctIndex: 0,
    explanation: 'Genesis 2 describes the creation of woman as a companion for man.',
    difficulty: 'medium',
  },
  {
    id: '21',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God use to create Eve?',
    options: ['A rib from Adam', 'Dust from the ground', 'Water from the river', 'A branch from the tree'],
    correctIndex: 0,
    explanation: 'God took a rib from Adam and formed Eve as his companion.',
    difficulty: 'medium',
  },
  {
    id: '22',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the name of the garden where Adam and Eve lived?',
    options: ['Garden of Eden', 'Garden of Gethsemane', 'Garden of Olives', 'Garden of Paradise'],
    correctIndex: 0,
    explanation: 'God planted the Garden of Eden in the east and placed Adam and Eve there.',
    difficulty: 'easy',
  },
  {
    id: '23',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent promise Eve if she ate the fruit?',
    options: ['Eyes would be opened, become like God', 'Eternal life', 'Power over animals', 'Wisdom without consequences'],
    correctIndex: 0,
    explanation: 'The serpent deceived Eve by saying eating the fruit would make her like God, knowing good and evil.',
    difficulty: 'hard',
  },
  {
    id: '24',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve do after eating the forbidden fruit?',
    options: ['Hid from God', 'Celebrated', 'Told the serpent', 'Ate more fruit'],
    correctIndex: 0,
    explanation: 'When they heard God walking, Adam and Eve hid among the trees of the garden.',
    difficulty: 'medium',
  },
  {
    id: '25',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve after the fall?',
    options: ['Garments of skin', 'Crowns of gold', 'Shoes of leather', 'Houses of wood'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and Eve to clothe their nakedness.',
    difficulty: 'hard',
  },
  {
    id: '26',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How many days did God take to create the world?',
    options: ['6 days', '7 days', '5 days', '8 days'],
    correctIndex: 0,
    explanation: 'God created the heavens and the earth in six days and rested on the seventh.',
    difficulty: 'medium',
  },
  {
    id: '27',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the tree called that Adam and Eve were forbidden to eat from?',
    options: ['Tree of the knowledge of good and evil', 'Tree of life', 'Tree of wisdom', 'Tree of fruit'],
    correctIndex: 0,
    explanation: 'God commanded them not to eat from the tree of the knowledge of good and evil.',
    difficulty: 'medium',
  },
  {
    id: '28',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the serpent would eat after the fall?',
    options: ['Dust', 'Fruit', 'Grass', 'Other serpents'],
    correctIndex: 0,
    explanation: 'God cursed the serpent to crawl on its belly and eat dust all the days of its life.',
    difficulty: 'hard',
  },
  {
    id: '29',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the order of creation on the first three days?',
    options: ['Light, firmament, dry land and plants', 'Plants, light, firmament', 'Dry land, light, firmament', 'Firmament, light, plants'],
    correctIndex: 0,
    explanation: 'Day 1: light; Day 2: firmament; Day 3: dry land and vegetation.',
    difficulty: 'hard',
  },
  {
    id: '30',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was created on the fourth, fifth, and sixth days?',
    options: ['Lights, sea creatures and birds, land animals and humans', 'Humans, birds, lights', 'Birds, lights, sea creatures', 'Land animals, humans, lights'],
    correctIndex: 0,
    explanation: 'Day 4: sun/moon/stars; Day 5: sea creatures/birds; Day 6: land animals/humans.',
    difficulty: 'hard',
  },
  {
    id: '31',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God rest on the seventh day?',
    options: ['He finished His work of creation', 'He was tired', 'To set an example', 'To contemplate'],
    correctIndex: 0,
    explanation: 'God had completed the work He had been doing, so He rested on the seventh day.',
    difficulty: 'medium',
  },
  {
    id: '32',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say about all His creation?',
    options: ['It was very good', 'It was good', 'It was excellent', 'It was perfect'],
    correctIndex: 0,
    explanation: 'After creating humans, God saw everything that He had made, and it was very good.',
    difficulty: 'medium',
  },
  {
    id: '33',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s first task in the garden?',
    options: ['To work and keep the garden', 'To name the animals', 'To build a house', 'To plant trees'],
    correctIndex: 0,
    explanation: 'God put Adam in the garden to work it and keep it.',
    difficulty: 'hard',
  },
  {
    id: '34',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Eve say the serpent told her about the fruit?',
    options: ['We will not surely die', 'It will make us sick', 'It will give us power', 'It will make us happy'],
    correctIndex: 0,
    explanation: 'Eve told God that the serpent said they would not surely die if they ate the fruit.',
    difficulty: 'hard',
  },
  {
    id: '35',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God do to the ground because of Adam\'s sin?',
    options: ['Cursed it with thorns and thistles', 'Made it fertile', 'Flooded it', 'Burned it'],
    correctIndex: 0,
    explanation: 'Because of Adam, the ground was cursed and would produce thorns and thistles.',
    difficulty: 'hard',
  },
  // New medium questions
  {
    id: '36',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was the purpose of the firmament created on the second day?',
    options: ['To separate waters above and below', 'To hold the stars', 'To provide light', 'To support land'],
    correctIndex: 0,
    explanation: 'The firmament divided the waters that were under it from the waters above it.',
    difficulty: 'medium',
  },
  {
    id: '37',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was vegetation created before the sun?',
    options: ['God provided light directly until the fourth day', 'The sun was not needed for plants', 'Plants grew at night', 'The moon provided light'],
    correctIndex: 0,
    explanation: 'God created light on day one, and vegetation on day three, before creating the sun on day four.',
    difficulty: 'medium',
  },
  {
    id: '38',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What blessing did God give to sea creatures and birds?',
    options: ['Be fruitful and multiply', 'Rule over the earth', 'Live forever', 'Speak languages'],
    correctIndex: 0,
    explanation: 'God blessed them to be fruitful, multiply, and fill the seas and skies.',
    difficulty: 'medium',
  },
  {
    id: '39',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did God create man according to Genesis 1?',
    options: ['In His image and likeness', 'From clay', 'From a tree', 'From water'],
    correctIndex: 0,
    explanation: 'God said, "Let us make mankind in our image, in our likeness."',
    difficulty: 'medium',
  },
  {
    id: '40',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God give humans dominion over?',
    options: ['Fish, birds, livestock, and earth', 'Angels', 'God Himself', 'Each other'],
    correctIndex: 0,
    explanation: 'God gave humans rule over the fish, birds, livestock, and all the earth.',
    difficulty: 'medium',
  },
  {
    id: '41',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s role in naming the animals?',
    options: ['To see if there was a suitable helper', 'To count them', 'To feed them', 'To hunt them'],
    correctIndex: 0,
    explanation: 'God brought animals to Adam to name them and find a companion.',
    difficulty: 'medium',
  },
  {
    id: '42',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God create Eve?',
    options: ['As a helper suitable for man', 'To work the garden', 'To name animals', 'To guard the trees'],
    correctIndex: 0,
    explanation: 'God said it was not good for man to be alone, so He made a helper.',
    difficulty: 'medium',
  },
  {
    id: '43',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What trees were in the midst of the garden?',
    options: ['Tree of life and tree of knowledge', 'Tree of wisdom and tree of fruit', 'Tree of good and tree of evil', 'Tree of peace and tree of war'],
    correctIndex: 0,
    explanation: 'The tree of life and the tree of the knowledge of good and evil were in the garden.',
    difficulty: 'medium',
  },
  {
    id: '44',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did the serpent question Eve about?',
    options: ['God\'s command regarding the tree', 'The garden\'s location', 'Adam\'s name', 'The weather'],
    correctIndex: 0,
    explanation: 'The serpent asked Eve about what God had said concerning eating from the tree.',
    difficulty: 'medium',
  },
  {
    id: '45',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How did Eve respond to the serpent\'s temptation?',
    options: ['She ate the fruit and gave some to Adam', 'She refused', 'She told God', 'She ran away'],
    correctIndex: 0,
    explanation: 'Eve took the fruit, ate it, and gave some to Adam who was with her.',
    difficulty: 'medium',
  },
  {
    id: '46',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did Adam and Eve realize after eating the fruit?',
    options: ['They were naked', 'They were hungry', 'They were tired', 'They were happy'],
    correctIndex: 0,
    explanation: 'Their eyes were opened, and they knew they were naked.',
    difficulty: 'medium',
  },
  {
    id: '47',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God ask Adam when He confronted him?',
    options: ['Where are you?', 'What have you done?', 'Why did you eat?', 'Who told you?'],
    correctIndex: 0,
    explanation: 'God called to Adam and asked, "Where are you?"',
    difficulty: 'medium',
  },
  {
    id: '48',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What was Adam\'s response to God\'s question?',
    options: ['I heard you and hid because I was naked', 'I ate the fruit', 'The serpent made me', 'I don\'t know'],
    correctIndex: 0,
    explanation: 'Adam admitted he hid because he was afraid due to his nakedness.',
    difficulty: 'medium',
  },
  {
    id: '49',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What curse did God place on the serpent?',
    options: ['Crawl on belly and eat dust', 'Lose its voice', 'Die immediately', 'Become invisible'],
    correctIndex: 0,
    explanation: 'The serpent was cursed to crawl on its belly and eat dust.',
    difficulty: 'medium',
  },
  {
    id: '50',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What enmity did God put between the serpent and the woman?',
    options: ['Between offspring', 'Between bodies', 'Between minds', 'Between homes'],
    correctIndex: 0,
    explanation: 'God put enmity between the serpent\'s offspring and the woman\'s offspring.',
    difficulty: 'medium',
  },
  {
    id: '51',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God say the woman\'s desire would be?',
    options: ['For her husband', 'For the garden', 'For the fruit', 'For the serpent'],
    correctIndex: 0,
    explanation: 'God said the woman\'s desire would be for her husband, and he would rule over her.',
    difficulty: 'medium',
  },
  {
    id: '52',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What name did Adam give to Eve?',
    options: ['Woman, because she was taken from man', 'Eve, because she was the mother of all living', 'Helper, because she helped him', 'Companion, because she was his friend'],
    correctIndex: 0,
    explanation: 'Adam called his wife\'s name Woman, for she was taken out of Man.',
    difficulty: 'medium',
  },
  {
    id: '53',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What did God make for Adam and Eve to wear?',
    options: ['Garments of skin', 'Leaves', 'Animal fur', 'Cloth'],
    correctIndex: 0,
    explanation: 'God made garments of skin for Adam and his wife and clothed them.',
    difficulty: 'medium',
  },
  {
    id: '54',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God drive Adam and Eve out of the garden?',
    options: ['To prevent them from eating from the tree of life', 'Because they were disobedient', 'To punish them', 'To start a new life'],
    correctIndex: 0,
    explanation: 'God drove them out lest they eat from the tree of life and live forever.',
    difficulty: 'medium',
  },
  {
    id: '55',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What guarded the way to the tree of life?',
    options: ['Cherubim and a flaming sword', 'Angels and a wall', 'Animals and thorns', 'God Himself'],
    correctIndex: 0,
    explanation: 'Cherubim and a flaming sword flashing back and forth guarded the way.',
    difficulty: 'medium',
  },
  // New hard questions
  {
    id: '56',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the significance of God creating in six days and resting on the seventh?',
    options: ['Establishes the pattern for human work and rest', 'Shows God\'s power', 'Demonstrates order', 'Teaches counting'],
    correctIndex: 0,
    explanation: 'The six-day creation and seventh-day rest set the foundation for the Sabbath and human rhythms.',
    difficulty: 'hard',
  },
  {
    id: '57',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why might God have created light before the sun?',
    options: ['To show His sovereignty over natural sources', 'The sun was not yet formed', 'Light existed independently', 'To confuse scientists'],
    correctIndex: 0,
    explanation: 'God\'s creation of light apart from the sun demonstrates His supreme authority over all sources of light.',
    difficulty: 'hard',
  },
  {
    id: '58',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the creation of humans "in God\'s image" imply?',
    options: ['Capacity for relationship and moral choice', 'Physical appearance', 'Immortality', 'Power over nature'],
    correctIndex: 0,
    explanation: 'Being made in God\'s image gives humans the unique ability to relate to God and make moral decisions.',
    difficulty: 'hard',
  },
  {
    id: '59',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was Adam\'s naming of animals significant?',
    options: ['Demonstrated his authority and revealed no equal companion', 'To learn their names', 'For scientific classification', 'To communicate with them'],
    correctIndex: 0,
    explanation: 'By naming animals, Adam exercised dominion and realized he needed a suitable partner.',
    difficulty: 'hard',
  },
  {
    id: '60',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the tree of life represent in the garden?',
    options: ['Eternal life and sustenance', 'Knowledge', 'Wisdom', 'Power'],
    correctIndex: 0,
    explanation: 'The tree of life offered immortality, which is why access was barred after the fall.',
    difficulty: 'hard',
  },
  {
    id: '61',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the serpent\'s temptation reveal deception?',
    options: ['Twists God\'s words and promises false benefits', 'Uses force', 'Ignores the command', 'Denies God\'s existence'],
    correctIndex: 0,
    explanation: 'The serpent misquotes God and promises godlike status, leading to disobedience.',
    difficulty: 'hard',
  },
  {
    id: '62',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does Adam and Eve hiding from God symbolize?',
    options: ['Recognition of guilt and broken relationship', 'Fear of punishment', 'Physical hiding', 'Avoiding conversation'],
    correctIndex: 0,
    explanation: 'Hiding symbolizes the shame and separation from God caused by sin.',
    difficulty: 'hard',
  },
  {
    id: '63',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God curse the ground for Adam\'s sake?',
    options: ['To reflect the broken relationship between man and creation', 'To make work harder', 'To punish the earth', 'To grow thorns'],
    correctIndex: 0,
    explanation: 'The curse on the ground mirrors how sin disrupted harmony in creation.',
    difficulty: 'hard',
  },
  {
    id: '64',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does the enmity between serpent\'s and woman\'s offspring foreshadow?',
    options: ['The ongoing battle between good and evil', 'Family conflicts', 'Animal attacks', 'Garden disputes'],
    correctIndex: 0,
    explanation: 'This points to the cosmic conflict between Satan\'s forces and humanity, culminating in Christ\'s victory.',
    difficulty: 'hard',
  },
  {
    id: '65',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does Eve\'s increased pain in childbirth relate to the fall?',
    options: ['Symbolizes the pain and sorrow sin brings to relationships', 'Physical only', 'Punishment for eating', 'Medical condition'],
    correctIndex: 0,
    explanation: 'The pain represents how sin complicates and brings suffering to human experiences.',
    difficulty: 'hard',
  },
  {
    id: '66',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What is the significance of God making garments of skin?',
    options: ['First sacrifice and covering of sin', 'Fashion statement', 'Protection from cold', 'Cultural tradition'],
    correctIndex: 0,
    explanation: 'The animal skins imply death and sacrifice, foreshadowing Christ\'s atonement.',
    difficulty: 'hard',
  },
  {
    id: '67',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why was the tree of life guarded after the fall?',
    options: ['To prevent eternal life in a fallen state', 'To protect it', 'To punish humans', 'To keep animals out'],
    correctIndex: 0,
    explanation: 'Immortality in sin would be a curse, so access to eternal life was blocked.',
    difficulty: 'hard',
  },
  {
    id: '68',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does Adam\'s naming of Eve as "Woman" signify?',
    options: ['Her origin from man and unity with him', 'Her beauty', 'Her role', 'Her name'],
    correctIndex: 0,
    explanation: 'Calling her "Woman" emphasizes she was taken from man, highlighting their oneness.',
    difficulty: 'hard',
  },
  {
    id: '69',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the creation account contrast with ancient Near Eastern myths?',
    options: ['God is sovereign and good, not in conflict with chaos', 'More violent', 'Less detailed', 'Similar stories'],
    correctIndex: 0,
    explanation: 'Unlike myths where gods battle chaos, God creates effortlessly and declares it good.',
    difficulty: 'hard',
  },
  {
    id: '70',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What theological truth does the Sabbath rest teach?',
    options: ['God\'s work is complete and sufficient', 'God needs rest', 'Creation was tiring', 'Time management'],
    correctIndex: 0,
    explanation: 'God\'s rest on the seventh day shows His creation is finished and perfect.',
    difficulty: 'hard',
  },
  {
    id: '71',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God curse the serpent to eat dust?',
    options: ['Represents defeat and humiliation', 'Dietary change', 'Punishment', 'New food source'],
    correctIndex: 0,
    explanation: 'Eating dust symbolizes the serpent\'s (Satan\'s) ultimate defeat and low status.',
    difficulty: 'hard',
  },
  {
    id: '72',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What does God\'s question "Where are you?" reveal about Him?',
    options: ['His desire for relationship despite sin', 'Anger', 'Confusion', 'Power'],
    correctIndex: 0,
    explanation: 'God seeks out the hiding humans, showing His loving pursuit even after disobedience.',
    difficulty: 'hard',
  },
  {
    id: '73',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'How does the fall affect human dominion over creation?',
    options: ['Makes it toilsome instead of harmonious', 'Increases power', 'Removes responsibility', 'Adds ease'],
    correctIndex: 0,
    explanation: 'Work becomes difficult, reflecting how sin disrupted the original harmony.',
    difficulty: 'hard',
  },
  {
    id: '74',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'What hope is implied in the curse on the serpent?',
    options: ['Ultimate victory through the woman\'s offspring', 'No hope', 'Serpent\'s victory', 'Peace'],
    correctIndex: 0,
    explanation: 'The promise of enmity and the serpent\'s defeat points to Christ\'s triumph over evil.',
    difficulty: 'hard',
  },
  {
    id: '75',
    segmentId: 'genesis_1_3',
    reference: 'Genesis 1–3',
    question: 'Why did God create Eve from Adam\'s rib rather than dust?',
    options: ['To show equality and unity in marriage', 'Easier method', 'Different material', 'Adam\'s preference'],
    correctIndex: 0,
    explanation: 'Taking from Adam\'s side signifies partnership and oneness in the marital relationship.',
    difficulty: 'hard',
  },
];

function getMixedQuestions(segmentId: string): Question[] {
  const all = mockQuestions.filter(q => q.segmentId === segmentId);
  const easy = all.filter(q => q.difficulty === 'easy');
  const medium = all.filter(q => q.difficulty === 'medium');
  const hard = all.filter(q => q.difficulty === 'hard');

  const shuffledEasy = shuffleArray(easy).slice(0, 5);
  const shuffledMedium = shuffleArray(medium).slice(0, 5);
  const shuffledHard = shuffleArray(hard).slice(0, 5);

  let selected = [...shuffledEasy, ...shuffledMedium, ...shuffledHard];

  if (selected.length < 15) {
    const takenIds = new Set(selected.map(q => q.id));
    const remaining = all.filter(q => !takenIds.has(q.id));
    const shuffledRemaining = shuffleArray(remaining);
    const needed = 15 - selected.length;
    selected = selected.concat(shuffledRemaining.slice(0, needed));
  }

  return shuffleArray(selected);
}

export function getQuestions(segmentId: string, difficulty: string): Question[] {
  if (difficulty === 'mixed') {
    return getMixedQuestions(segmentId);
  }

  const filtered = mockQuestions.filter(q => q.segmentId === segmentId);

  if (filtered.length === 0) {
    return [];
  }

  const byDifficulty = filtered.filter(q => q.difficulty === difficulty);

  if (byDifficulty.length >= 5) {
    return shuffleArray(byDifficulty).slice(0, 5);
  }

  // Fallback to other difficulties
  const otherDifficulties = ['easy', 'medium', 'hard'].filter(d => d !== difficulty);
  let additional: Question[] = [];

  for (const diff of otherDifficulties) {
    const more = filtered.filter(q => q.difficulty === diff);
    additional = additional.concat(more);
    if (additional.length >= 5) break;
  }

  const combined = byDifficulty.concat(additional);
  return shuffleArray(combined).slice(0, 5);
}
